import React, { useCallback, useEffect, useState } from 'react';
import {Plus, Save, ExternalLink, Trash2} from 'lucide-react';
import {Bot, RefreshCw} from '../../components/AnimatedIcon';
import { api, fmtDate, openTelegramLink } from '../../lib/api';
import { useToast } from '../../components/Toast';
import '../../premium-polish.css';
import { Notice, Loader, EmptyState } from '../../components/ui';
export default function DeployBotsTab() {
  const { addToast } = useToast();
  const [selectedType,setSelectedType]=useState(false),[selectedBot,setSelectedBot]=useState(null);
  const [tab,setTab]=useState('plans'),[config,setConfig]=useState(null),[rows,setRows]=useState([]),[coupons,setCoupons]=useState([]);
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(null),[firstMessage,setFirstMessage]=useState('');
  const [coupon,setCoupon]=useState({code:'',percent:10,max_uses:100,expires_at:'',enabled:true});
  const load=useCallback(async()=>{
    try {const [c,r,cp]=await Promise.all([api.get('/api/admin/welcome-config'),api.get('/api/admin/bot-deploys'),api.get('/api/admin/welcome-coupons')]);if(c?.api_version!==2||!c.health||!Array.isArray(c.plans)||!Array.isArray(r)||!Array.isArray(cp))throw new Error('Server update incomplete: latest files ke baad zayro-panel ko restart karein.');setConfig(c);setRows(r);setCoupons(cp);setError('');}
    catch(e){setError(e.message);}
  },[]);
  useEffect(()=>{load();},[load]);
  async function run(fn, message='Saved') {setBusy(true);try{const r=await fn();addToast(message,'success');return r;}catch(e){addToast(e.message,'error');return null;}finally{setBusy(false);}}
  async function control(action) {
    if (['stop_all','start_all','reminders'].includes(action)&&!window.confirm('Apply this action to bots in the Welcome Bot engine?')) return;
    const data=await run(()=>api.post('/api/admin/welcome-controls',{action}),'Action completed');
    setResult(data);if(action==='get_defaults'&&data)setFirstMessage(data.first_message||'');
  }
  async function botAction(row,action) {
    if (action!=='info'&&!window.confirm(`${action} @${row.bot_username}?`)) return;
    const r=await run(()=>api.post(`/api/admin/bot-deploys/${row.id}/action`,{action}),'Bot status checked');
    setResult(r);await load();
  }
  if(!selectedType)return <div className="stack gap-16"><h2>Bot management</h2><p className="hint">Select a bot service to manage pricing, deployments and controls.</p><div className="admin-selection-grid"><button className="admin-selection-card" onClick={()=>setSelectedType(true)}><Bot size={32}/><strong>Welcome Bot</strong><span>{rows.filter(r=>r.kind==='deploy').length} deployments · Plans, renewals & controls</span><b>Manage Welcome Bot →</b></button></div></div>;
  if (!config&&!error) return <Loader label="Loading Welcome Bot management…"/>;
  return <div className="welcome-admin"><button className="btn btn-soft" onClick={()=>setSelectedType(false)}>← All bot services</button><div className="flex-row between wrap gap-10"><div><h2><Bot size={22}/> Deploy Bot</h2><p className="hint">Welcome Bot · pricing, coupons, deployments and runtime controls</p></div><button className="btn btn-soft btn-sm" disabled={busy} onClick={load}><RefreshCw size={14}/> Refresh</button></div>
    {error&&<Notice tone="danger">{error}<p>VPS par latest code pull karke <code>pm2 restart zayro-panel --update-env</code> chalayein. Phir Refresh dabayein.</p></Notice>}
    {config&&<><Notice tone={config.health.ready?'ok':'warn'}>{config.health.ready?'Welcome Bot engine is connected.':'Bot engine connect nahi hai. Isliye customer abhi purchase nahi kar sakta.'}{config.health.manager_username&&<button className="btn btn-ghost btn-xs" onClick={()=>openTelegramLink(`https://t.me/${config.health.manager_username}`)}>Open Telegram controls <ExternalLink size={13}/></button>}</Notice>
    <section className="card card-pad stack gap-12"><b>Welcome Bot shuru karne ke 3 steps</b><div className="welcome-setup-checks"><p><strong>{config.health.ready?'✓':'1.'} Bot engine</strong><span>{config.health.ready?'Connected':config.setup?.configured?'Config mili hai; zayro-welcome process / database check karein.':'VPS par bash scripts/setup-welcome-bot.sh chalayein. Alag manager bot token use karein.'}</span></p><p><strong>{config.plans.some(p=>p.enabled)?'✓':'2.'} Plans & prices</strong><span>Purchase / renewal prices set karein aur Publish this plan tick karein.</span></p><p><strong>{config.enabled?'✓':'3.'} Purchases</strong><span>Enable Welcome Bot purchases tick karke Save plans dabayein.</span></p></div><small className="hint">Engine connected + published plan + purchases enabled: teeno ready hone par booking khulegi.</small></section>
    <nav className="welcome-admin-nav" aria-label="Deploy Bot sections">{[['deployments','Deployments'],['plans','Plans & pricing'],['coupons','Coupons'],['controls','Bot controls']].map(([key,label])=><button key={key} className={`btn btn-sm ${tab===key?'btn-primary':'btn-soft'}`} onClick={()=>{setTab(key);setResult(null);}}>{label}</button>)}</nav>
    {tab==='plans'&&<form className="stack gap-16" onSubmit={async e=>{e.preventDefault();await run(()=>api.post('/api/admin/welcome-config',config));}}><div className="card card-pad"><label className="flex-row gap-10"><input type="checkbox" checked={config.enabled} onChange={e=>setConfig({...config,enabled:e.target.checked})}/> Enable Welcome Bot purchases</label><p className="hint">Prices aur wallet payments direct ₹ mein hain. Unpublished plans cannot be bought.</p></div>{config.plans.map((p,i)=><div className="card card-pad stack gap-12" key={p.key}><div className="flex-row between"><b>{p.name}</b><button type="button" className="btn btn-ghost btn-xs" aria-label={`Remove ${p.name}`} onClick={()=>setConfig({...config,plans:config.plans.filter((_,idx)=>idx!==i)})}><Trash2 size={15}/></button></div><div className="welcome-plan-editor">{[['name','Plan name','text'],['days','Validity (days)','number'],['price','Purchase price ₹','number'],['original_price','Original price ₹ (optional)','number'],['renewal_price','Renewal price ₹','number'],['max_channels','Channel limit','number']].map(([key,label,type])=><label className="field" key={key}><span className="label">{label}</span><input className="input" required type={type} min={key==='days'||key==='max_channels'?1:0} step="1" value={p[key]} onChange={e=>setConfig({...config,plans:config.plans.map((x,n)=>n===i?{...x,[key]:type==='number'?Number(e.target.value):e.target.value}:x)})}/></label>)}</div><label className="flex-row gap-8"><input type="checkbox" checked={p.enabled} onChange={e=>setConfig({...config,plans:config.plans.map((x,n)=>n===i?{...x,enabled:e.target.checked}:x)})}/> Publish this plan</label></div>)}<div className="btn-group"><button type="button" className="btn btn-soft" onClick={()=>setConfig({...config,plans:[...config.plans,{key:`plan_${Date.now()}`,name:'New plan',days:30,price:0,original_price:0,renewal_price:0,max_channels:5,enabled:false}]})} disabled={config.plans.length>=12}><Plus size={15}/> Add plan</button><button className="btn btn-primary" disabled={busy}><Save size={15}/> Save plans</button></div></form>}
    {tab==='deployments'&&<><label className="field"><span className="label">Select deployed bot</span><select className="input" value={selectedBot||''} onChange={e=>setSelectedBot(e.target.value||null)}><option value="">Choose a bot…</option>{rows.filter(r=>r.kind==='deploy').map(r=><option key={r.id} value={r.bot_username}>@{r.bot_username} · #{r.id}</option>)}</select></label>{!rows.length?<EmptyState icon={Bot} title="No purchases yet" text="Configure and publish plans to accept your first deployment."/>:rows.filter(r=>r.bot_username===selectedBot).map(r=><article className="card card-pad stack gap-12" key={r.id}><div className="flex-row between wrap"><b>#{r.id} · @{r.bot_username}{r.kind==='renew'?' · Renewal':''}</b><span className={`status ${r.status==='active'?'ok':r.refunded?'danger':'warn'}`}>{r.refunded?'Refunded':r.status}</span></div><p className="hint">Customer: {r.username||r.user_id} · Bot owner ID: {r.admin_tg_id}<br/>{r.plan.name} · ₹{r.coins} · {fmtDate(r.created_at)}{r.expires_at&&<> · Expires {fmtDate(r.expires_at)}</>}</p>{r.kind==='deploy'&&!r.refunded&&!['pending','provisioning'].includes(r.status)&&<div className="btn-group">{['info','start','stop','restart'].map(a=><button key={a} className="btn btn-soft btn-sm" disabled={busy} onClick={()=>botAction(r,a)}>{a.charAt(0).toUpperCase()+a.slice(1)}</button>)}</div>}{['pending','provisioning'].includes(r.status)&&<Notice>Awaiting a confirmed runtime result. Retried automatically; uncertain requests are not charged again or manually marked Live.</Notice>}</article>)}</>}
    {tab==='coupons'&&<><form className="card card-pad stack gap-12" onSubmit={async e=>{e.preventDefault();const r=await run(()=>api.post('/api/admin/welcome-coupons',coupon));if(r)await load();}}><h3>Create / update coupon</h3><div className="welcome-plan-editor">{[['code','Code','text'],['percent','Discount %','number'],['max_uses','Total uses','number'],['expires_at','Expires at','datetime-local']].map(([key,label,type])=><label className="field" key={key}><span className="label">{label}</span><input required className="input" type={type} value={coupon[key]} onChange={e=>setCoupon({...coupon,[key]:e.target.value})}/></label>)}</div><label className="flex-row gap-8"><input type="checkbox" checked={coupon.enabled} onChange={e=>setCoupon({...coupon,enabled:e.target.checked})}/> Enabled · one use per customer</label><button className="btn btn-primary" disabled={busy}>Save coupon</button></form>{coupons.map(c=><div className="row-item" key={c.code}><span className="row-main"><b>{c.code}</b><small className="row-sub">{c.percent}% · {c.used}/{c.max_uses} used · {c.enabled?'Enabled':'Disabled'}</small></span><button className="btn btn-soft btn-xs" onClick={()=>setCoupon({...c,expires_at:c.expires_at.slice(0,16)})}>Edit</button></div>)}</>}
    {tab==='controls'&&<><div className="card card-pad stack gap-16"><h3>Engine controls</h3><div className="btn-group">{[['summary','Statistics'],['users','All users'],['subscriptions','Subscriptions'],['check_expiry','Check expiry'],['reminders','Send reminders'],['start_all','Start all bots'],['stop_all','Stop all bots'],['get_defaults','Default first message']].map(([a,label])=><button key={a} className="btn btn-soft btn-sm" disabled={busy||!config.health.ready} onClick={()=>control(a)}>{label}</button>)}</div></div><div className="card card-pad stack gap-12"><h3>Original bot admin panel</h3><p className="hint">The linked engine keeps its original admin controls: add account/subscription, welcome media & button builder, broadcast, leave recovery, channel settings and diagnostics. Open the manager bot with your configured operator Telegram account and send /admin. Customers use their own Telegram ID to manage only their bots.</p><button className="btn btn-primary" disabled={!config.health.manager_username} onClick={()=>openTelegramLink(`https://t.me/${config.health.manager_username}`)}>Open full bot controls <ExternalLink size={15}/></button></div>{firstMessage&&<form className="card card-pad stack gap-12" onSubmit={async e=>{e.preventDefault();await run(()=>api.post('/api/admin/welcome-controls',{action:'save_defaults',first_message:firstMessage}));}}><label className="label" htmlFor="first-message">Default first message</label><textarea id="first-message" className="input" rows={5} value={firstMessage} onChange={e=>setFirstMessage(e.target.value)}/><button className="btn btn-primary" disabled={busy}>Save message</button></form>}</>}
    {result&&<section className="card card-pad"><div className="flex-row between"><b>Result</b><button className="btn btn-ghost btn-xs" onClick={()=>setResult(null)}>Close</button></div><pre className="welcome-admin-result">{JSON.stringify(result,null,2)}</pre></section>}
    </>}
  </div>;
}
