import React,{useEffect,useRef,useState} from 'react';
import {Plus,Search,ChevronRight,Trash2,Pencil,ArrowLeft,CheckCircle2} from 'lucide-react';
import {User as Users,RefreshCw} from '../../components/AnimatedIcon';
import {api} from '../../lib/api';
import ResellerReport,{DateRange,todayRange,money,paise,Summary} from '../../components/ResellerReport';
import ResellerActivity from '../../components/ResellerActivity';
import ResellerDialog from '../../components/ResellerDialog';
import '../../reseller.css';
const defaults={status:'active',apk_percent:30,bot_percent:25,site_percent:20,note:'',version:0};
const stateName=r=>r?.removed_at?'Removed':r?.status||'active';
export default function ResellersTab(){
 const [range,setRange]=useState(todayRange),[data,setData]=useState(null),[detail,setDetail]=useState(null),[selected,setSelected]=useState(null),[form,setForm]=useState(defaults),[query,setQuery]=useState(''),[customers,setCustomers]=useState([]),[filter,setFilter]=useState(''),[status,setStatus]=useState('all'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0),[modal,setModal]=useState(null),[draftUser,setDraftUser]=useState(null),[popupError,setPopupError]=useState(''),[searching,setSearching]=useState(false),[reportTab,setReportTab]=useState('overview');
 const top=useRef(null),showRemoved=status==='removed';
 useEffect(()=>{let stale=false;setLoading(true);setError('');api.get(`/api/admin/resellers?summary=1&include_removed=${showRemoved?'1':'0'}`).then(d=>{if(!stale)setData(d);}).catch(e=>{if(!stale)setError(e.message);}).finally(()=>{if(!stale)setLoading(false);});return()=>{stale=true;};},[revision,showRemoved]);
 useEffect(()=>{let stale=false;setDetail(null);if(!selected)return;setError('');api.get(`/api/admin/resellers/${selected.id}?${new URLSearchParams(range)}`).then(d=>{if(!stale)setDetail(d);}).catch(e=>{if(!stale)setError(e.message);});return()=>{stale=true;};},[selected,range,revision]);
 useEffect(()=>{let stale=false;setCustomers([]);setSearching(!!query.trim());const timer=setTimeout(()=>{if(!query.trim())return;api.get(`/api/admin/resellers/customers?q=${encodeURIComponent(query)}`).then(r=>{if(!stale)setCustomers(r);}).catch(e=>{if(!stale)setPopupError(e.message);}).finally(()=>{if(!stale)setSearching(false);});},300);return()=>{stale=true;clearTimeout(timer);};},[query]);
 const openReport=r=>{setSelected({id:r.user_id,username:r.username});setReportTab('overview');setRange(todayRange());setError('');top.current?.scrollIntoView({block:'start',behavior:'smooth'});};
 const close=()=>{if(!busy){setModal(null);setPopupError('');}};
 const add=()=>{setDraftUser(null);setQuery('');setCustomers([]);setForm({...defaults});setPopupError('');setModal({type:'edit',adding:true});};
 const chooseCustomer=async u=>{setBusy(true);setPopupError('');try{let p=null;try{p=(await api.get(`/api/admin/resellers/${u.id}`)).profile;}catch(e){if(e.status!==404)throw e;}setDraftUser(u);setForm(p?{...p,status:p.removed_at?'active':p.status}:{...defaults});}catch(e){setPopupError(e.message);}finally{setBusy(false);}};
 const edit=()=>{setDraftUser({id:selected.id,username:selected.username});setForm({...detail.profile,status:detail.profile.removed_at?'active':detail.profile.status});setPopupError('');setModal({type:'edit',adding:false});};
 const review=e=>{e.preventDefault();if(!draftUser||busy)return;for(const key of ['apk_percent','bot_percent','site_percent']){if(form[key]===''||!Number.isInteger(Number(form[key]))||Number(form[key])<0||Number(form[key])>95){setPopupError('Enter whole discount percentages between 0 and 95.');return;}}setPopupError('');setModal({type:'review',adding:modal.adding});};
 const save=async()=>{if(busy||!draftUser)return;setBusy(true);setPopupError('');try{await api.post(`/api/admin/resellers/${draftUser.id}`,form);setRevision(v=>v+1);setModal({type:'success',title:'Reseller saved',message:`${draftUser.username} now has ${form.status} access. New purchases use these rates; existing orders and wallet are unchanged.`});}catch(e){setPopupError(e.message);}finally{setBusy(false);}};
 const remove=async()=>{if(busy||!detail)return;setBusy(true);setPopupError('');try{await api.post(`/api/admin/resellers/${selected.id}/remove`,{version:detail.profile.version});setSelected(null);setDetail(null);setRevision(v=>v+1);setModal({type:'success',title:'Reseller removed',message:'Partner access has been removed. Wallet, customer account and all past orders are safe. Find this partner under Removed to restore access.'});}catch(e){setPopupError(e.message);}finally{setBusy(false);}};
 const rows=(data?.rows||[]).filter(r=>(showRemoved?!!r.removed_at:!r.removed_at&&(status==='all'||r.status===status))&&`${r.username} ${r.user_id} ${r.telegram_id}`.toLowerCase().includes(filter.toLowerCase()));
 const editBody=<form id="reseller-editor" noValidate onSubmit={review} className="rs-edit-form">{modal?.adding&&!draftUser?<><label>Find a customer<div className="rs-search"><Search size={17}/><input className="input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Username, user ID or Telegram ID" disabled={busy}/></div></label><div className="rs-customer-results">{customers.map(u=><button type="button" key={u.id} disabled={busy} onClick={()=>chooseCustomer(u)}><span className="rs-avatar">{u.username?.slice(0,2).toUpperCase()}</span><span><b>{u.username}</b><small>#{u.id} · TG {u.telegram_id||'—'}</small></span><ChevronRight size={18}/></button>)}</div><p className="rs-muted">{searching?'Searching customers…':query&&!customers.length?'No matching customers. Try a different username or ID.':'Select an existing customer. No separate wallet is created.'}</p></>:<><div className="rs-selected-user"><Users size={24}/><div><b>{draftUser?.username}</b><small>Customer #{draftUser?.id}</small></div>{modal?.adding&&<button type="button" className="btn btn-soft btn-sm" onClick={()=>setDraftUser(null)}>Change</button>}</div><label>Status<select aria-label="Status" className="input" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active · reseller prices</option><option value="suspended">Suspended · stop new purchases</option><option value="disabled">Disabled · normal customer prices</option></select></label><div className="rs-discount-inputs">{[['apk_percent','APK OFF %'],['bot_percent','Bot OFF %'],['site_percent','Website OFF %']].map(([key,label])=><label key={key}>{label}<input className="input" type="number" min="0" max="95" step="1" required value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div><label>Private admin note<textarea className="input" maxLength={500} value={form.note} onChange={e=>setForm({...form,note:e.target.value})}/></label><p className="rs-muted">Discounts apply to current selling prices, including renewals. Coupons cannot stack. Past orders keep their original prices.</p></>}</form>;
 const dialogTitle=modal?.type==='edit'?(modal.adding?'Add reseller':'Edit reseller'):modal?.type==='review'?'Confirm reseller settings':modal?.type==='remove'?'Remove reseller access?':modal?.title||'';
 return <div className="rs-page" ref={top}>
 {!selected?<><section className="rs-directory-head"><div><span className="rs-kicker"><Users size={16}/> PARTNER NETWORK</span><h1>Resellers</h1><p>Select a partner to open their complete report.</p></div><div className="rs-actions"><button className="btn btn-soft" aria-label="Refresh resellers" onClick={()=>setRevision(v=>v+1)}><RefreshCw size={16}/></button><button className="btn btn-primary" onClick={add}><Plus size={17}/> Add reseller</button></div></section>
 <div className="rs-stats rs-directory-stats">{[['Enrolled',data?.total],['Active',data?.active],['Removed',data?.removed]].map(([label,n])=><div className="rs-stat" key={label}><span>{label}</span><strong>{n??'—'}</strong></div>)}</div>
 <div className="rs-filters"><input aria-label="Filter resellers" className="input" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Search your resellers…"/><select aria-label="Filter status" className="input" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All resellers</option><option value="active">Active</option><option value="suspended">Suspended</option><option value="disabled">Disabled</option><option value="removed">Removed · history & restore</option></select></div>
 {loading?<p>Loading partners…</p>:<div className="rs-partner-grid">{rows.map(r=><button className="rs-partner-card" key={r.user_id} onClick={()=>openReport(r)} aria-label={`View report for ${r.username||'#'+r.user_id}`}><div className="rs-partner-top"><span className="rs-avatar">{(r.username||'R').slice(0,2).toUpperCase()}</span><div><h3>{r.username||'Customer #'+r.user_id}</h3><small>#{r.user_id} · TG {r.telegram_id||'—'}</small></div><ChevronRight size={20}/></div><span className={`rs-badge ${r.status}`}>{stateName(r)}</span><div className="rs-rate-chips"><span>APK <b>{r.apk_percent}%</b></span><span>Bot <b>{r.bot_percent}%</b></span><span>Website <b>{r.site_percent}%</b></span></div><div className="rs-partner-bottom"><div><small>Wallet</small><strong>{money(r.wallet)}</strong></div><div><small>{r.orders} reseller orders</small><strong>{paise(r.charged_paise-r.refunds_paise)}</strong></div></div><span className="rs-open-report">View full report →</span></button>)}{!rows.length&&<div className="card card-pad"><h3>No resellers here yet</h3><p className="rs-muted">Use Add reseller to enrol a customer, or change your search/filter.</p></div>}</div>}</>:<>
 <button className="btn btn-soft rs-back" onClick={()=>{setSelected(null);setDetail(null);setError('');}}><ArrowLeft size={16}/> All resellers</button>
 <section className="rs-profile-head"><span className="rs-avatar">{(selected.username||'R').slice(0,2).toUpperCase()}</span><div className="grow"><span className="rs-kicker">RESELLER REPORT · #{selected.id}</span><h1>{selected.username||'Reseller'}</h1>{detail&&<span className={`rs-badge ${detail.profile.status}`}>{stateName(detail.profile)}</span>}</div><div className="rs-actions"><button className="btn btn-soft" aria-label="Refresh partner report" disabled={busy} onClick={()=>setRevision(v=>v+1)}><RefreshCw size={16}/></button><button className="btn btn-soft" disabled={!detail} onClick={edit}><Pencil size={15}/>{detail?.profile.removed_at?'Restore reseller':'Edit rates'}</button>{detail&&!detail.profile.removed_at&&<button className="btn rs-danger-btn" onClick={()=>{setPopupError('');setModal({type:'remove'});}}><Trash2 size={15}/> Remove</button>}</div></section>
 {!detail&&!error?<p>Loading partner report…</p>:detail&&<><div className="rs-profile-strip"><span>Current wallet <b>{money(detail.user?.coins)}</b></span><span>APK <b>{detail.profile.apk_percent}% OFF</b></span><span>Bot <b>{detail.profile.bot_percent}% OFF</b></span><span>Website <b>{detail.profile.site_percent}% OFF</b></span></div><DateRange range={range} setRange={setRange}/><div className="rs-report-tabs" role="tablist" aria-label="Report sections">{[['overview','Overview'],['payments','Orders & payments'],['history','Admin history']].map(([key,label])=><button key={key} role="tab" aria-selected={reportTab===key} className={reportTab===key?'selected':''} onClick={()=>setReportTab(key)}>{label}</button>)}</div>
 {reportTab==='overview'?<><ResellerActivity activity={detail.activity}/><Summary title="Lifetime wallet spend · reseller orders" stats={detail.lifetime}/><Summary title="Selected dates · order charges and refunds" stats={detail.period}/><p className="rs-muted">Spend is not your business profit. Open Orders & payments for the ledger, deposits, refunds and CSV export.</p></>:reportTab==='payments'?<ResellerReport data={detail}/>:<section className="card card-pad"><h3>Admin change history</h3><p className="rs-muted">Latest 50 changes. Timestamps below are UTC.</p>{detail.audit.map(a=>{const after=JSON.parse(a.after_json);return <div className="rs-audit" key={a.id}><b>{a.actor} · {a.created_at}</b><p>{stateName(after)} · APK {after.apk_percent}% / Bot {after.bot_percent}% / Website {after.site_percent}%</p>{after.note&&<small>{after.note}</small>}</div>;})}</section>}</>}
 </>}
 {error&&<div className="rs-error" role="alert">{error} <button className="btn btn-soft btn-sm" onClick={()=>setRevision(v=>v+1)}>Retry</button></div>}
 <ResellerDialog open={!!modal} title={dialogTitle} subtitle={modal?.type==='review'?draftUser?.username:modal?.type==='remove'?selected?.username:null} onClose={close} busy={busy} tone={modal?.type==='remove'?'danger':modal?.type==='success'?'success':''} footer={modal?.type==='success'?<button className="btn btn-primary" onClick={close}>Done</button>:<><button className="btn btn-soft" disabled={busy} onClick={()=>modal?.type==='review'?setModal({...modal,type:'edit'}):close()}>{modal?.type==='review'?'Back':'Cancel'}</button>{modal?.type==='edit'?<button form="reseller-editor" type="submit" className="btn btn-primary" disabled={busy||!draftUser}>Review settings</button>:<button className={`btn ${modal?.type==='remove'?'rs-danger-btn':'btn-primary'}`} disabled={busy} onClick={modal?.type==='remove'?remove:save}>{busy?'Saving…':modal?.type==='remove'?'Remove reseller':'Confirm & save'}</button>}</>}>
 {modal?.type==='edit'?editBody:modal?.type==='review'?<><div className="rs-confirm-rates">{[['APK',form.apk_percent],['Bot',form.bot_percent],['Website',form.site_percent]].map(([label,n])=><div key={label}><small>{label}</small><strong>{n}% OFF</strong></div>)}</div><p>Access: <b>{form.status}</b></p><p className="rs-muted">Only future purchases use these settings. Existing order prices, refunds and wallet balance will not change.</p></>:modal?.type==='remove'?<><div className="rs-remove-warning"><Trash2 size={28}/><p>This customer will lose reseller discounts and return to regular prices.</p></div><ul className="rs-safe-list"><li>Wallet balance stays unchanged</li><li>Orders, refunds and reports stay available</li><li>Restore access anytime from Removed</li></ul></>:modal?.type==='success'?<div className="rs-success-content" role="status"><CheckCircle2 size={46}/><p>{modal.message}</p></div>:null}
 {popupError&&<div className="rs-error" role="alert">{popupError}</div>}
 </ResellerDialog>
 </div>;
}
