import React,{useEffect,useState} from 'react';
import {Plus, Save, Upload, ArrowUp, ArrowDown} from 'lucide-react';
import {Globe, Package, RefreshCw} from '../../components/AnimatedIcon';
import {api,fmtDate} from '../../lib/api';
import {SectionHead,Notice,Loader,Sheet} from '../../components/ui';
import {useToast} from '../../components/Toast';
import '../../site-store.css';
import '../../premium-polish.css';
const blank=()=>({name:'',image:'',url:'',enabled:false,plans:[{key:'days7',days:7,price:699,original_price:999}]});
export default function SiteStoreTab(){
 const {addToast}=useToast();const [data,setData]=useState(null),[draft,setDraft]=useState(blank),[selected,setSelected]=useState(null),[stock,setStock]=useState([]),[credentials,setCredentials]=useState({username:'',password:''}),[restock,setRestock]=useState({}),[filter,setFilter]=useState('all'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[coupon,setCoupon]=useState({code:'',percent:10,max_uses:100,expires_at:'',enabled:true});
 const [removeName,setRemoveName]=useState(null);
 const [editing,setEditing]=useState(false);
 const load=async()=>{const d=await api.get('/api/admin/site-store');setData(d);};
 useEffect(()=>{load().catch(e=>setError(e.message));},[]);
 const run=async fn=>{setBusy(true);setError('');try{const message=await fn();await load();addToast(typeof message==='string'?message:'Saved','success');}catch(e){setError(e.message);}finally{setBusy(false);}};
 const inventory=async id=>{setSelected(id);setStock(await api.get(`/api/admin/site-store/products/${id}/stock`));};
 const select=p=>{setEditing(true);setDraft({...p});setError('');setBusy(true);inventory(p.id).catch(e=>setError(e.message)).finally(()=>setBusy(false));};
 const upload=async file=>{if(!file)return;await run(async()=>{const form=new FormData();form.append('image',file);const r=await api.postForm('/api/admin/site-store/image',form);setDraft(d=>({...d,image:r.image}));});};
 const shown=stock.filter(s=>filter==='all'||(filter==='expiring'?s.state==='assigned'&&s.expires_at<=Date.now()+86400000:s.state===filter));
 return <div className="stack gap-16 site-admin-stock"><SectionHead icon={Globe} title="Website store" sub="Manual accounts · ₹ plans · expiry reminders" action={<button className="btn btn-soft" disabled={busy} onClick={()=>run(async()=>{if(selected)await inventory(selected);})}><RefreshCw size={14}/> Refresh</button>}/>
 <Sheet open={removeName!==null} title="Delete website stock" onClose={()=>{if(!busy)setRemoveName(null);}}><div className="purchase-result"><p>All available and expired accounts for <b>{data?.products.find(p=>p.id===selected)?.name}</b> will be removed from inventory. Active sold accounts and history are protected.</p><label className="field"><span className="label">Type the website name to confirm</span><input className="input" autoFocus value={removeName||''} onChange={e=>setRemoveName(e.target.value)}/></label><div className="btn-group"><button className="btn btn-soft" disabled={busy} onClick={()=>setRemoveName(null)}>Cancel</button><button className="btn btn-primary" disabled={busy||removeName!==data?.products.find(p=>p.id===selected)?.name} onClick={()=>run(async()=>{const r=await api.post(`/api/admin/site-store/products/${selected}/remove-stock`,{confirm:removeName});setRemoveName(null);await inventory(selected);return `${r.removed} removed · ${r.protected} active protected`;})}>Confirm removal</button></div></div></Sheet>
 {error&&<Notice tone="danger">{error}</Notice>}
 <Notice tone="info">Website par disable/password change MANUAL hai. Expired account ka password actual website par change karke hi restock karein. Telegram admin ID / bot ko Settings mein configure karein.</Notice>
 {!data?<Loader/>:<>
 <div className="flex-row between wrap gap-8"><span className="hint">Notifications pending: {data.notifications.pending||0} · Retrying: {data.notifications.retrying||0}</span><button className="btn btn-soft btn-sm" disabled={busy} onClick={()=>run(()=>api.post('/api/admin/site-store/reminders',{}))}>Run reminder check</button></div>
 {!editing&&<div className="admin-selection-grid">{data.products.map((p,index)=><article className="admin-order-card" key={p.id}><div className="admin-order-controls"><span>Position {index+1}</span><button className="btn btn-soft btn-xs" aria-label={`Move ${p.name} up`} disabled={busy||index===0} onClick={()=>run(()=>api.post(`/api/admin/site-store/products/${p.id}/move`,{direction:'up'}))}><ArrowUp size={16}/></button><button className="btn btn-soft btn-xs" aria-label={`Move ${p.name} down`} disabled={busy||index===data.products.length-1} onClick={()=>run(()=>api.post(`/api/admin/site-store/products/${p.id}/move`,{direction:'down'}))}><ArrowDown size={16}/></button></div><button className="admin-selection-card" style={{textAlign:'left',color:'inherit'}} key={p.id} onClick={()=>select(p)}>{p.image&&<img src={p.image} alt=""/>}<strong>{p.name} · {p.enabled?'Published':'Hidden'}</strong><div className="flex-row wrap gap-8">{[['Accounts',p.counts.total],['Available',p.counts.available],['Active',p.counts.active],['Expiring ≤24h',p.counts.expiring],['Expired / change password',p.counts.expired],['Lifetime allocations',p.counts.sold]].map(([label,value])=><span className="chip" key={label}>{label}: {value||0}</span>)}</div><span className="hint">Manage website →</span></button></article>)}</div>}
 <button className="btn btn-soft" onClick={()=>{setEditing(true);setDraft(blank());setSelected(null);setStock([]);}}><Plus size={14}/> New website</button>
 {editing&&<><div className="admin-detail-header"><b>{draft.name||'New website'}</b><button className="btn btn-soft" disabled={busy} onClick={()=>{setEditing(false);setSelected(null);setStock([]);}}>← All websites</button></div><form className="card card-pad stack gap-12" onSubmit={e=>{e.preventDefault();run(async()=>{const r=await api.post('/api/admin/site-store/products',draft);setDraft(d=>({...d,id:r.id}));await inventory(r.id);});}}>
 <h3>{draft.id?'Edit website':'Add website'}</h3>
 {[['name','Website name'],['url','Website login URL (HTTPS)'],['image','Image URL (or upload below)']].map(([key,label])=><label className="field" key={key}><span className="label">{label}</span><input className="input" required={key!=='image'} value={draft[key]} onChange={e=>setDraft({...draft,[key]:e.target.value})}/></label>)}
 <label className="btn btn-soft"><Upload size={14}/> Upload image<input type="file" accept="image/png,image/jpeg,image/webp" hidden disabled={busy} onChange={e=>upload(e.target.files?.[0])}/></label>{draft.image&&<img className="site-logo" src={draft.image} alt="Website preview"/>}
 <label><input type="checkbox" checked={draft.enabled} onChange={e=>setDraft({...draft,enabled:e.target.checked})}/> Publish website</label>
 <p className="hint">Plans: days, price ₹, original price ₹ (optional). Same prices apply to renewals.</p>
 {draft.plans.map((p,i)=><div className="stack gap-8" key={p.key}><div className="site-admin-plans">{[['days','Days',1],['price','Price ₹',1],['original_price','Original ₹',0]].map(([key,label,min])=><label className="field" key={key}><span className="label">{label}</span><input className="input" type="number" min={min} required value={p[key]} onChange={e=>setDraft({...draft,plans:draft.plans.map((x,n)=>n===i?{...x,[key]:Number(e.target.value)}:x)})}/></label>)}</div><button type="button" className="btn btn-ghost btn-xs" disabled={draft.plans.length===1} onClick={()=>setDraft({...draft,plans:draft.plans.filter((_,n)=>n!==i)})}>Remove plan</button></div>)}
 <div className="btn-group"><button type="button" className="btn btn-soft" disabled={draft.plans.length>=12} onClick={()=>setDraft({...draft,plans:[...draft.plans,{key:`p${Date.now()}`,days:30,price:999,original_price:0}]})}>Add plan</button><button className="btn btn-primary" disabled={busy}><Save size={14}/> Save website</button></div>
 </form>
 {selected&&<><form className="card card-pad stack gap-12" onSubmit={e=>{e.preventDefault();run(async()=>{await api.post(`/api/admin/site-store/products/${selected}/stock`,credentials);setCredentials({username:'',password:''});await inventory(selected);});}}><SectionHead icon={Package} title="Add ready account" sub={`Website #${selected} · One account per stock unit`}/><input className="input" aria-label="Account ID" placeholder="Account number / username" autoComplete="off" required value={credentials.username} onChange={e=>setCredentials({...credentials,username:e.target.value})}/><input className="input" aria-label="Account password" placeholder="Website password (at least 6 characters)" type="password" autoComplete="new-password" minLength={6} required value={credentials.password} onChange={e=>setCredentials({...credentials,password:e.target.value})}/><button className="btn btn-primary" disabled={busy}>Add stock</button></form>
 <div className="bulk-delete"><div><b>Delete available / expired stock</b><p className="hint">Active sold accounts and order history stay protected. Removed records are archived.</p></div><button className="btn btn-soft" disabled={busy||!stock.some(s=>['available','expired'].includes(s.state))} onClick={()=>setRemoveName('')}>Delete stock in bulk</button></div>
 <div className="flex-row gap-8"><b>Inventory</b><select className="input" aria-label="Inventory filter" value={filter} onChange={e=>setFilter(e.target.value)}>{['all','available','assigned','expiring','expired'].map(x=><option key={x}>{x}</option>)}</select></div>
 {!shown.length&&<p className="hint">No accounts in this category.</p>}{shown.map(s=><div className="card card-pad stack gap-10" key={s.id}><strong>{s.username} · {s.state}</strong><span className="hint">Stock #{s.id} · Cycle {s.generation}{s.user_id?` · Customer #${s.user_id} · Account #${s.lease_id}`:''}{s.expires_at?` · ${fmtDate(new Date(s.expires_at).toISOString())}`:''}</span>{s.state==='expired'&&<><input className="input" type="password" autoComplete="new-password" placeholder="New password after changing on website" value={restock[s.id]?.password||''} onChange={e=>setRestock({...restock,[s.id]:{...restock[s.id],password:e.target.value}})}/><label><input type="checkbox" checked={restock[s.id]?.confirmed||false} onChange={e=>setRestock({...restock,[s.id]:{...restock[s.id],confirmed:e.target.checked}})}/> I disabled old access and changed the password on the website.</label><button className="btn btn-primary" disabled={busy||!restock[s.id]?.confirmed} onClick={()=>run(async()=>{await api.post(`/api/admin/site-store/stock/${s.id}/restock`,restock[s.id]);setRestock(r=>({...r,[s.id]:{}}));await inventory(selected);})}>Return to available stock</button></>}</div>)}</>}
 <form className="card card-pad stack gap-12" onSubmit={e=>{e.preventDefault();run(()=>api.post('/api/admin/site-store/coupons',{...coupon,expires_at:new Date(coupon.expires_at).toISOString()}));}}><h3>Website coupons (store-wide)</h3>{[['code','Coupon code','text'],['percent','Discount %','number'],['max_uses','Maximum uses','number'],['expires_at','Expiry (local time)','datetime-local']].map(([key,label,type])=><label className="field" key={key}><span className="label">{label}</span><input className="input" type={type} required value={coupon[key]} onChange={e=>setCoupon({...coupon,[key]:e.target.value})}/></label>)}<label><input type="checkbox" checked={coupon.enabled} onChange={e=>setCoupon({...coupon,enabled:e.target.checked})}/> Enabled</label><button className="btn btn-primary" disabled={busy}>Save coupon</button>{data.coupons.map(c=><button type="button" className="btn btn-soft" key={c.code} onClick={()=>{const d=new Date(c.expires_at);setCoupon({...c,expires_at:new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)});}}>{c.code} · {c.percent}% · {c.used}/{c.max_uses} used · {c.enabled?'Enabled':'Disabled'}</button>)}</form>
 </>}
 </>}
 </div>;
}
