'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),DB=require('better-sqlite3');
const {createDeposits}=require('../utils/deposit-payments'),{decidePayment}=require('../utils/payment-decisions');
const {createMonitor}=require('../utils/crypto-monitor');
const TRON='T9yD14Nj9j7xAB4dbGeiX9h8unkKHxuWwb';
function setup(t){const db=new DB(':memory:');t.after(()=>db.close());db.exec(`CREATE TABLE users(id INTEGER PRIMARY KEY,coins INTEGER,telegram_id TEXT);INSERT INTO users VALUES(1,0,'111'),(2,0,'222');CREATE TABLE settings(key TEXT PRIMARY KEY,value TEXT);CREATE TABLE coin_requests(id INTEGER PRIMARY KEY,user_id INTEGER,coins_requested INTEGER,amount_paid REAL,utr TEXT,screenshot_file TEXT,status TEXT DEFAULT 'pending',approved_by TEXT);`);for(const [k,v]of Object.entries({usdt_trc20_address:TRON,usdt_bep20_address:'0x'+'a'.repeat(40),usdt_inr_rate:'100',usdt_bonus_percent:'5',site_url:'https://panel.test'}))db.prepare('INSERT INTO settings VALUES(?,?)').run(k,v);let time=1700000000000;const env={USDT_TRC20_AUTO:'true',USDT_BEP20_AUTO:'true',TRONGRID_API_KEY:'fixture',BSC_RPC_URL:'https://rpc.invalid'};const service=createDeposits(db,{now:()=>time,env});return {db,service,env,now:()=>time,advance:n=>time+=n,quote:(network='trc20',user=1)=>service.quote(user,{method:network,amount:'10'}),event:(q,tx='a'.repeat(64),offset=1000)=>({network:q.method,txid:tx,address:q.address,micro:db.prepare('SELECT amount_micro FROM crypto_invoices WHERE quote_id=?').get(q.id).amount_micro,time:q.created_at+offset})};}
test('both networks reserve exact amounts forever, retain rate and bonus, and scope status to owner',t=>{const f=setup(t);for(const network of ['trc20','bep20']){const a=f.quote(network),b=f.quote(network,2);assert(a.automatic);assert.equal(a.amount,'10.000001');assert.equal(b.amount,'10.000002');assert.equal(a.credit_inr,1050);assert.equal(f.service.automatic.view(a.id,2),null);f.advance(1800001);assert.equal(f.service.automatic.view(a.id,1).payment_state,'expired');const c=f.quote(network);assert.equal(c.amount,'10.000003');}});
test('confirmed on-time transfers credit only once even after restart and duplicate scans',t=>{const f=setup(t);for(const network of ['trc20','bep20']){const q=f.quote(network),e=f.event(q);assert.equal(f.service.automatic.observe(e),'credited');assert.equal(f.service.automatic.observe(e),'credited');assert.equal(f.service.automatic.view(q.id,1).payment_state,'paid');}assert.equal(f.db.prepare('SELECT coins FROM users WHERE id=1').get().coins,2100);const fresh=createDeposits(f.db,{now:f.now,env:f.env});const q=f.db.prepare("SELECT * FROM deposit_quotes WHERE method='trc20'").get();fresh.automatic.observe(f.event(q));assert.equal(f.db.prepare('SELECT coins FROM users WHERE id=1').get().coins,2100);assert.equal(f.db.prepare('SELECT count(*) n FROM crypto_credits').get().n,2);});
test('late, wrong amount, old and other-address transfers never credit automatically',t=>{const f=setup(t);const q=f.quote();for(const [index,e]of [f.event(q,'1'.repeat(64),1800001),{...f.event(q,'2'.repeat(64)),micro:'10000000'},f.event(q,'3'.repeat(64),-1000),{...f.event(q,'4'.repeat(64)),address:'other'}].entries()){assert.notEqual(f.service.automatic.observe(e),'credited',String(index));}assert.equal(f.db.prepare('SELECT coins FROM users WHERE id=1').get().coins,0);assert.equal(f.service.automatic.view(q.id,1).payment_state,'late');});
test('late proof uses actual received amount; human approval and scanner cannot credit twice',t=>{const f=setup(t),q=f.quote();const e=f.event(q,'b'.repeat(64),1800001);f.service.automatic.observe(e);const r=f.service.submit(1,{quote_id:q.id,utr:e.txid,received_amount:'5',note:'sent less'},'proof.png');assert.equal(r.row.coins_requested,525);assert.equal(r.row.payment_amount,'5.000000');assert.equal(f.db.prepare('SELECT coins FROM users WHERE id=1').get().coins,0);assert.equal(decidePayment(f.db,r.row.id,'approve','admin').status,'approved');assert(decidePayment(f.db,r.row.id,'approve','admin').error);f.service.automatic.observe(e);assert.equal(f.db.prepare('SELECT coins FROM users WHERE id=1').get().coins,525);});
test('a proof race pauses automatic credit, and same TXID cannot approve a second request',t=>{const f=setup(t),q=f.quote('bep20'),e=f.event(q);const r=f.service.submit(1,{quote_id:q.id,utr:e.txid,received_amount:q.amount},'proof.png');assert.equal(f.service.automatic.observe(e),'review');assert.equal(decidePayment(f.db,r.row.id,'approve','admin').status,'approved');const other=f.quote('bep20',2);assert.throws(()=>f.service.submit(2,{quote_id:other.id,utr:e.txid,received_amount:other.amount},'proof.png'));assert.equal(f.db.prepare('SELECT coins FROM users WHERE id=1').get().coins,1050);});
test('transaction rollback preserves retry when wallet update cannot complete',t=>{const f=setup(t),q=f.quote();f.db.exec("CREATE TRIGGER stop_credit BEFORE UPDATE OF coins ON users BEGIN SELECT RAISE(IGNORE); END;");assert.throws(()=>f.service.automatic.observe(f.event(q)));assert.equal(f.db.prepare('SELECT count(*) n FROM crypto_credits').get().n,0);assert.equal(f.db.prepare('SELECT count(*) n FROM coin_requests').get().n,0);});
test('monitor failure never advances cursor; overlap guarded; notifications link to wallet',async t=>{const f=setup(t),q=f.quote();let entered,release;const started=new Promise(r=>entered=r),gate=new Promise(r=>release=r);let calls=0;const reader=async(_w,c,cb)=>{calls++;entered();await gate;cb(f.event(q));throw Error('provider failed after event');};const notices=[];const monitor=createMonitor(f.db,f.service.automatic,{now:f.now,readers:{trc20:reader},notify:async(...args)=>{notices.push(args);return {message_id:1};}});const running=monitor.tick();await started;await monitor.tick();release();await running;assert.equal(calls,1);assert.equal(f.db.prepare('SELECT cursor FROM crypto_cursors').get().cursor,'{}');assert.equal(f.db.prepare('SELECT coins FROM users WHERE id=1').get().coins,1050);assert.equal(notices.length,1);assert.match(notices[0][2].inline_keyboard[0][0].web_app.url,/tab=wallet/);await monitor.tick();assert.equal(f.db.prepare('SELECT coins FROM users WHERE id=1').get().coins,1050);assert.equal(notices.length,1);});
test('auto mode is opt-in; invalid TRON checksum rejects without consuming a quote',t=>{const f=setup(t);f.env.USDT_TRC20_AUTO='false';assert(!f.quote().automatic);f.env.USDT_TRC20_AUTO='true';f.db.prepare("UPDATE settings SET value=? WHERE key='usdt_trc20_address'").run('T'+'A'.repeat(33));const before=f.db.prepare('SELECT count(*) n FROM deposit_quotes').get().n;assert.throws(()=>f.quote(),/checksum/);assert.equal(f.db.prepare('SELECT count(*) n FROM deposit_quotes').get().n,before);});
test('admin correction changes the proposed credit, retains audit trail, and paid status reports actual credit',t=>{const f=setup(t),q=f.quote('bep20');const r=f.service.submit(1,{quote_id:q.id,utr:'e'.repeat(64),received_amount:'9'},'proof.png');assert.equal(r.row.coins_requested,945);assert.equal(f.service.correctReceived(r.row.id,'5').credit_inr,525);assert.equal(f.db.prepare('SELECT count(*) n FROM crypto_review_adjustments').get().n,1);assert.equal(decidePayment(f.db,r.row.id,'approve','admin').status,'approved');assert.equal(f.service.automatic.view(q.id,1).credit_inr,525);assert.throws(()=>f.service.correctReceived(r.row.id,'10'));});
test('legacy saved bonus is preserved on same-amount proof and prorated for corrected amount',t=>{const f=setup(t);f.env.USDT_TRC20_AUTO='false';const q=f.quote();f.db.prepare('UPDATE deposit_quotes SET bonus_bps=0 WHERE id=?').run(q.id);const r=f.service.submit(1,{quote_id:q.id,utr:'f'.repeat(64),received_amount:'10'},'proof.png');assert.equal(r.row.coins_requested,1050);assert.equal(f.service.correctReceived(r.row.id,'5').credit_inr,525);});
test('deleted customers go to orphan review without blocking later confirmed transfers',t=>{const f=setup(t),a=f.quote(),b=f.quote('trc20',2);f.db.prepare('DELETE FROM users WHERE id=1').run();assert.equal(f.service.automatic.observe(f.event(a)),'orphan');assert.equal(f.service.automatic.observe(f.event(b,'c'.repeat(64))),'credited');assert.equal(f.db.prepare('SELECT coins FROM users WHERE id=2').get().coins,1050);});
