'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),Database=require('better-sqlite3');
const {createDeposits,validateSettings}=require('../utils/deposit-payments');
const {decidePayment}=require('../utils/payment-decisions');
function fixture(t){const db=new Database(':memory:');t.after(()=>db.close());db.exec(`CREATE TABLE users(id INTEGER PRIMARY KEY,coins INTEGER);INSERT INTO users VALUES(1,0),(2,0);CREATE TABLE settings(key TEXT PRIMARY KEY,value TEXT);CREATE TABLE coin_requests(id INTEGER PRIMARY KEY,user_id INTEGER,coins_requested INTEGER,amount_paid REAL,utr TEXT,screenshot_file TEXT,status TEXT DEFAULT 'pending',approved_by TEXT);`);const settings={upi_id:'demo@bank',site_name:'Demo & Test',usdt_trc20_address:'T'+'A'.repeat(33),usdt_bep20_address:'0x'+'a'.repeat(40),usdt_inr_rate:'92.50',usdt_bonus_percent:'5'};for(const [k,v] of Object.entries(settings))db.prepare('INSERT INTO settings VALUES(?,?)').run(k,v);return {db,service:createDeposits(db)};}
test('UPI QR payload contains encoded payee and exact selected INR amount',t=>{const {service}=fixture(t);for(const amount of ['100','300','1234']){const q=service.quote(1,{method:'upi',amount});const url=new URL(q.payload);assert.equal(url.protocol,'upi:');assert.equal(url.hostname,'pay');assert.equal(url.searchParams.get('pa'),'demo@bank');assert.equal(url.searchParams.get('pn'),'Demo & Test');assert.equal(url.searchParams.get('am'),Number(amount).toFixed(2));assert.equal(url.searchParams.get('cu'),'INR');assert.equal(q.credit_inr,Number(amount));assert.equal(q.bonus_inr,0);}});
test('strict limits reject fractional INR, malformed/huge/non-finite amounts and missing config',t=>{const {db,service}=fixture(t);for(const amount of ['0','-1','1.5','Infinity','NaN','1e4','1000001'])assert.throws(()=>service.quote(1,{method:'upi',amount}));for(const amount of ['9.99','10001','10.001'])assert.throws(()=>service.quote(1,{method:'trc20',amount}));assert.throws(()=>service.quote(1,{method:'other',amount:'100'}));db.exec("DELETE FROM settings WHERE key='usdt_inr_rate'");assert.throws(()=>service.quote(1,{method:'trc20',amount:'10'}));db.exec("DELETE FROM settings WHERE key='upi_id'");assert.throws(()=>service.quote(1,{method:'upi',amount:'100'}));});
test('crypto quotes snapshot network, rate, bonus and address; proof cannot alter credit',t=>{const {db,service}=fixture(t);for(const method of ['trc20','bep20']){const q=service.quote(1,{method,amount:'10.25'});assert.equal(q.base_inr,948);assert.equal(q.bonus_inr,47);assert.equal(q.credit_inr,995);assert.equal(q.payload,q.address);const r=service.submit(1,{quote_id:q.id,utr:'a'.repeat(64),coins:999999,amount:999999},'proof.png');assert.equal(r.row.coins_requested,995);assert.equal(r.row.payment_method,method);assert.equal(db.prepare('SELECT coins FROM users WHERE id=1').get().coins,0);}const q=service.quote(1,{method:'trc20',amount:'10'});db.exec("UPDATE settings SET value='200' WHERE key='usdt_inr_rate'");const r=service.submit(1,{quote_id:q.id,utr:'b'.repeat(64)},'proof.png');assert.equal(r.row.coins_requested,971);assert.equal(r.row.payment_rate,92.5);});
test('quote ownership, proof, reference validation, duplicate reference and submit idempotency',t=>{const {db,service}=fixture(t);const q=service.quote(1,{method:'upi',amount:'100'});assert.throws(()=>service.submit(2,{quote_id:q.id,utr:'123456789012'},'proof.png'));assert.throws(()=>service.submit(1,{quote_id:q.id,utr:'1234'},'proof.png'));assert.throws(()=>service.submit(1,{quote_id:q.id,utr:'123456789012'},''));const r=service.submit(1,{quote_id:q.id,utr:'123456789012'},'proof.png');assert.equal(service.submit(1,{quote_id:q.id,utr:'123456789012'},'again.png').reused,true);assert.equal(db.prepare('SELECT count(*) n FROM coin_requests').get().n,1);const q2=service.quote(2,{method:'upi',amount:'100'});assert.throws(()=>service.submit(2,{quote_id:q2.id,utr:'123456789012'},'proof.png'));assert(!decidePayment(db,r.row.id,'approve','admin').error);assert.equal(db.prepare('SELECT coins FROM users WHERE id=1').get().coins,100);assert.equal(decidePayment(db,r.row.id,'approve','admin').error,'Already processed');assert.equal(db.prepare('SELECT coins FROM users WHERE id=1').get().coins,100);});
test('normalized TXID blocks uppercase or 0x-prefixed replay on the same network',t=>{const {service}=fixture(t);const a=service.quote(1,{method:'bep20',amount:'10'}),b=service.quote(2,{method:'bep20',amount:'10'});service.submit(1,{quote_id:a.id,utr:'0x'+'A'.repeat(64)},'proof.png');assert.throws(()=>service.submit(2,{quote_id:b.id,utr:'a'.repeat(64)},'proof.png'));});
test('payment config validation and per-user quote rate limits',t=>{const {service}=fixture(t);for(const body of [{upi_id:'bad'},{usdt_trc20_address:'bad'},{usdt_bep20_address:'bad'},{usdt_inr_rate:'0'},{usdt_inr_rate:'-1'},{usdt_bonus_percent:'51'},{upi_id:['demo@bank']}])assert.throws(()=>validateSettings(body));validateSettings({upi_id:'demo@bank',usdt_bonus_percent:'0',usdt_trc20_address:''});for(let i=0;i<30;i++)service.quote(1,{method:'upi',amount:'100'});assert.throws(()=>service.quote(1,{method:'upi',amount:'100'}),/Too many/);assert(service.quote(2,{method:'upi',amount:'100'}).id);});
