'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),express=require('express'),crypto=require('node:crypto');
const {sameOriginMutation}=require('../utils/http-security');
const {verifyTelegramWebAppData}=require('../utils/telegram-access');
const token='123456789:proxy-test-only';
function proof(){const p=new URLSearchParams({auth_date:String(Math.floor(Date.now()/1000)),user:JSON.stringify({id:42})});const secret=crypto.createHmac('sha256','WebAppData').update(token).digest();p.set('hash',crypto.createHmac('sha256',secret).update([...p.keys()].sort().map(k=>`${k}=${p.get(k)}`).join('\n')).digest('hex'));return p.toString();}
async function fixture(t){const app=express();app.set('trust proxy',false);app.use((req,res,next)=>sameOriginMutation(req,res,next,'https://panel.example.test/'));app.use(express.json());app.post('/api/auth/telegram-webapp',(req,res)=>{if(!verifyTelegramWebAppData(req.body.initData,token))return res.status(401).json({code:'TG_AUTH_INVALID'});res.json({success:true});});const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(()=>new Promise(r=>server.close(r)));return `http://127.0.0.1:${server.address().port}/api/auth/telegram-webapp`;}
function options(origin,initData=proof(),extra={}){return {method:'POST',headers:{'Content-Type':'application/json',Origin:origin,...extra},body:JSON.stringify({initData})};}
test('HTTPS configured origin can authenticate over an HTTP proxy upstream with rewritten Host',async t=>{const url=await fixture(t);const res=await fetch(url,options('https://panel.example.test'));assert.equal(res.status,200);assert.equal((await res.json()).success,true);});
test('configured public origin does not allow foreign, null, downgraded or cross-site origins',async t=>{const url=await fixture(t);for(const origin of ['https://attacker.test','null','http://panel.example.test','https://panel.example.test.attacker.test'])assert.equal((await fetch(url,options(origin))).status,403);assert.equal((await fetch(url,options('https://panel.example.test',proof(),{'Sec-Fetch-Site':'cross-site'}))).status,403);});
test('spoofed proxy headers cannot add a new allowed origin',async t=>{const url=await fixture(t);assert.equal((await fetch(url,options('https://attacker.test',proof(),{'X-Forwarded-Host':'attacker.test','X-Forwarded-Proto':'https'}))).status,403);});
test('same configured origin still requires a valid Telegram signature',async t=>{const url=await fixture(t);const res=await fetch(url,options('https://panel.example.test','auth_date=1&hash=fake'));assert.equal(res.status,401);assert.equal((await res.json()).code,'TG_AUTH_INVALID');});
