'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),DB=require('better-sqlite3');
const {isPaymentAdmin,decidePayment}=require('../utils/payment-decisions');
const {ownsUpload}=require('../utils/private-upload-access');
function fixture(t){const db=new DB(':memory:');t.after(()=>db.close());db.exec("CREATE TABLE users(id INTEGER PRIMARY KEY,coins INTEGER);INSERT INTO users VALUES(1,0),(2,10);CREATE TABLE coin_requests(id INTEGER PRIMARY KEY,user_id INTEGER,coins_requested INTEGER,status TEXT,approved_by TEXT,screenshot_file TEXT);INSERT INTO coin_requests VALUES(1,1,100,'pending',NULL,'proof.png');CREATE TABLE orders(user_id INTEGER,icon_file TEXT);INSERT INTO orders VALUES(1,'icon.png');");return db;}
test('payment authorization checks exact clicking user, never group ID or partial matches',()=>{assert(isPaymentAdmin(99,'99,100'));for(const id of [9,-10099,0,undefined,'99x'])assert(!isPaymentAdmin(id,'99,-10099'));assert(!isPaymentAdmin(99,'-10099'));});
test('payment decision is atomic, idempotent and cannot reject approved funds',t=>{const db=fixture(t);assert.equal(decidePayment(db,1,'approve','test').status,'approved');assert.equal(db.prepare('SELECT coins FROM users WHERE id=1').get().coins,100);assert(decidePayment(db,1,'approve','test').error);assert(decidePayment(db,1,'reject','test').error);assert.equal(db.prepare('SELECT coins FROM users WHERE id=1').get().coins,100);});
test('payment rollback restores pending status if user credit fails',t=>{const db=fixture(t);db.exec('DELETE FROM users WHERE id=1');assert.throws(()=>decidePayment(db,1,'approve','test'));assert.equal(db.prepare('SELECT status FROM coin_requests WHERE id=1').get().status,'pending');});
test('private proofs/icons require exact owner and unknown uploads are denied',t=>{const db=fixture(t);assert(ownsUpload(db,1,'proof.png'));assert(ownsUpload(db,1,'icon.png'));assert(!ownsUpload(db,2,'proof.png'));assert(!ownsUpload(db,2,'icon.png'));assert(!ownsUpload(db,null,'proof.png'));assert(!ownsUpload(db,1,'random.html'));});
