'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),Database=require('better-sqlite3'),crypto=require('crypto');
const {createStore,DAY}=require('../utils/site-store');
function fixture(t){const db=new Database(':memory:');t.after(()=>db.close());db.exec("CREATE TABLE users(id INTEGER PRIMARY KEY,coins INTEGER,telegram_id TEXT);INSERT INTO users VALUES(1,10000,'111'),(2,10000,'222');CREATE TABLE settings(key TEXT PRIMARY KEY,value TEXT);INSERT INTO settings VALUES('telegram_admin_id','999'),('site_url','https://example.test');");let time=Date.parse('2026-10-07T00:00:00Z'),sent=[],deliver=true;const key=crypto.randomBytes(32);const service=createStore(db,key,{now:()=>time,notify:async(chat,text)=>{if(!deliver)return null;sent.push({chat,text});return {message_id:sent.length};}});const product=service.saveProduct({name:'Demo website',image:'',url:'https://example.test/login',enabled:true,plans:[{key:'week',days:7,price:700,original_price:999},{key:'month',days:30,price:1000}]});const add=name=>service.addStock(product,{username:name,password:'secret-'+name});const buy=(user=1,extra={})=>{const b={product_id:product,plan_key:'week',quantity:1,request_key:crypto.randomUUID(),...extra};const q=service.quote(user,b);return service.purchase(user,{...b,expected_total:q.total,expected_same_account:q.same_account});};return {db,service,product,key,add,buy,sent,advance:n=>time+=n,offline:()=>deliver=false,online:()=>deliver=true};}
test('atomic stock allocation, encrypted credentials and idempotent wallet purchase',t=>{const f=fixture(t);f.add('a');f.add('b');const key=crypto.randomUUID();const r=f.buy(1,{quantity:2,request_key:key});assert.equal(r.total,1400);assert.equal(f.db.prepare('SELECT coins FROM users WHERE id=1').get().coins,8600);assert.equal(f.service.products()[0].stock,0);assert.equal(f.service.accounts(1).length,2);assert.equal(f.service.accounts(2).length,0);assert.doesNotMatch(JSON.stringify(f.service.inventory(f.product)),/secret-|cipher/);assert.doesNotMatch(f.db.prepare('SELECT cipher FROM site_stock LIMIT 1').get().cipher,/secret-/);assert.equal(f.service.purchase(1,{request_key:key}).id,r.id);assert.equal(f.db.prepare('SELECT coins FROM users WHERE id=1').get().coins,8600);assert.throws(()=>f.buy(2),/stock/);});
test('active renewal keeps account, extends from expiry, and ignores stock exhaustion',t=>{const f=fixture(t);f.add('a');const r=f.buy();const a=f.service.accounts(1)[0];f.advance(DAY);const renew=f.buy(1,{renew_id:r.lease_ids[0],plan_key:'month'});assert.deepEqual(renew.lease_ids,r.lease_ids);const b=f.service.accounts(1)[0];assert.equal(b.password,a.password);assert.equal(b.expires_at,a.expires_at+30*DAY);assert.equal(f.service.inventory(f.product)[0].state,'assigned');assert.throws(()=>f.buy(2,{renew_id:a.id}),/renewal/);});
test('expired renewal gives different account, restock needs changed password and old owner never sees new credentials',t=>{const f=fixture(t);f.add('a');const original=f.buy();const old=f.service.accounts(1)[0];f.advance(7*DAY);assert.equal(f.service.accounts(1)[0].password,null);assert.throws(()=>f.buy(1,{renew_id:old.id}),/stock/);assert.throws(()=>f.service.restock(old.stock_id,{password:'secret-a',confirmed:true}),/previous password/);assert.throws(()=>f.service.restock(old.stock_id,{password:'rotated-a'}),/Confirm/);f.service.restock(old.stock_id,{password:'rotated-a',confirmed:true});assert.throws(()=>f.buy(1,{renew_id:old.id}),/stock/);f.add('b');const renew=f.buy(1,{renew_id:old.id});assert.notEqual(renew.lease_ids[0],original.lease_ids[0]);assert.equal(f.service.accounts(1)[0].username,'b');f.buy(2);assert.equal(f.service.accounts(2)[0].password,'rotated-a');assert.equal(f.service.accounts(1).find(x=>x.id===old.id).password,null);assert.throws(()=>f.buy(1,{renew_id:old.id}),/latest replacement/);});
test('rollback leaves wallet/stock intact for insufficient balance, stale quotes, invalid quantity and coupon exhaustion',t=>{const f=fixture(t);f.add('a');f.db.prepare('UPDATE users SET coins=10 WHERE id=1').run();assert.throws(()=>f.buy(),/balance/);assert.equal(f.service.products()[0].stock,1);assert.throws(()=>f.buy(1,{quantity:0}),/Quantity/);assert.throws(()=>f.service.purchase(2,{product_id:f.product,plan_key:'week',request_key:crypto.randomUUID(),expected_total:1,expected_same_account:false}),/changed/);assert.equal(f.db.prepare('SELECT coins FROM users WHERE id=2').get().coins,10000);f.service.coupon({code:'SAVE',percent:10,max_uses:1,expires_at:'2099-01-01',enabled:true});assert.equal(f.buy(2,{coupon:'SAVE'}).total,630);f.add('b');assert.throws(()=>f.buy(1,{coupon:'SAVE'}),/Coupon/);});
test('24h reminders and expiry notifications target admin/user, deduplicate, retry and survive restart',async t=>{const f=fixture(t);f.add('a');f.buy();await f.service.tick();assert.equal(f.sent.length,1);f.advance(6*DAY);await f.service.tick();assert.equal(f.sent.filter(s=>s.text.includes('Expires within')).length,2);await f.service.tick();assert.equal(f.sent.length,3);f.offline();f.advance(DAY);await f.service.tick();assert.equal(f.sent.length,3);f.online();f.advance(300001);await f.service.tick();assert.equal(f.sent.filter(s=>s.text.includes('— Expired')).length,2);assert.equal(f.service.inventory(f.product)[0].state,'expired');const s=createStore(f.db,f.key,{now:()=>Date.parse('2026-10-15T00:00:00Z'),notify:async()=>{throw Error('Should not resend');}});await s.tick();assert.equal(f.db.prepare('SELECT count(*) n FROM site_notifications WHERE sent_at IS NULL').get().n,0);});
test('renewal cancels stale expiry jobs and delayed notifications never disable a restocked account',async t=>{const f=fixture(t);f.add('a');f.buy();f.offline();f.advance(6*DAY);await f.service.tick();f.buy(1,{renew_id:1});f.online();f.advance(300001);await f.service.tick();assert.equal(f.sent.filter(s=>s.text.includes('Expires within')).length,0);f.advance(8*DAY);f.offline();await f.service.tick();f.service.restock(1,{password:'rotated-secret',confirmed:true});f.buy(2);f.online();f.advance(300001);await f.service.tick();assert.equal(f.sent.filter(s=>s.chat==='999'&&s.text.includes('Disable this account')).length,0);});
test('all-or-nothing batch allocation rolls back if any insert fails',t=>{const f=fixture(t);f.add('a');f.add('b');f.db.exec("CREATE TRIGGER reject_second BEFORE INSERT ON site_leases WHEN NEW.stock_id=2 BEGIN SELECT RAISE(ABORT,'test failure'); END;");assert.throws(()=>f.buy(1,{quantity:2}),/test failure/);assert.equal(f.service.products()[0].stock,2);assert.equal(f.db.prepare('SELECT coins FROM users WHERE id=1').get().coins,10000);assert.equal(f.db.prepare('SELECT count(*) n FROM site_sales').get().n,0);});
test('quotes cannot silently switch an active renewal to replacement at expiry',t=>{const f=fixture(t);f.add('a');f.add('b');f.buy();const body={product_id:f.product,plan_key:'week',renew_id:1,request_key:crypto.randomUUID(),expected_total:700,expected_same_account:true};f.advance(7*DAY);assert.throws(()=>f.service.purchase(1,body),/changed/);assert.equal(f.service.products()[0].stock,1);assert.equal(f.db.prepare('SELECT coins FROM users WHERE id=1').get().coins,9300);});
test('stock cannot be recycled while active and no password from any previous cycle can be reused',t=>{const f=fixture(t);f.add('a');f.buy();assert.throws(()=>f.service.restock(1,{password:'rotated-a',confirmed:true}),/Only expired/);f.advance(7*DAY);f.service.restock(1,{password:'rotated-a',confirmed:true});f.buy(2);f.advance(7*DAY);assert.throws(()=>f.service.restock(1,{password:'secret-a',confirmed:true}),/previous password/);assert.equal(f.service.accounts(1)[0].password,null);assert.equal(f.service.accounts(2)[0].password,null);});
test('restoring the wrong encryption key fails closed rather than selling unreadable credentials',t=>{const f=fixture(t);f.add('a');assert.throws(()=>createStore(f.db,crypto.randomBytes(32)));assert.equal(f.service.products()[0].stock,1);});
test('bulk stock parses numbered lists and blank lines, encrypts all passwords, and rejects duplicate/invalid batches atomically',t=>{
 const f=fixture(t);const result=f.service.addBulkStock(f.product,'01. demo-one — password-one\n\n02. demo-two — password-two\n03) demo-three - password-three\ndemo-four – password-four');assert.equal(result.added,4);assert.equal(result.available,4);
 assert.throws(()=>f.service.addBulkStock(f.product,'new-one — password-new\ndemo-one — different-secret'),/Line 2: account already exists/);
 assert.throws(()=>f.service.addBulkStock(f.product,'new-one — password-new\nnew-one — other-secret'),/Line 2: duplicate/);
 assert.throws(()=>f.service.addBulkStock(f.product,'new-one — password-new\n\nbad-line'),/Line 3/);
 assert.throws(()=>f.service.addBulkStock(f.product,'new-one — short'),/password length/);
 assert.throws(()=>f.service.addBulkStock(f.product,''),/1–200/);
 assert.throws(()=>f.service.addBulkStock(f.product,Array.from({length:201},(_,i)=>`user${i} — password`).join('\n')),/1–200/);
 assert.equal(f.service.products()[0].stock,4);assert.doesNotMatch(JSON.stringify(f.service.inventory(f.product)),/password-one|cipher/);
 assert.equal(f.db.prepare('SELECT count(*) n FROM site_password_history').get().n,4);
});
test('bulk transaction rolls back every account if one database insert fails',t=>{const f=fixture(t);f.db.exec("CREATE TRIGGER fail_bulk BEFORE INSERT ON site_stock WHEN NEW.username='second' BEGIN SELECT RAISE(ABORT,'insert failed'); END;");assert.throws(()=>f.service.addBulkStock(f.product,'first — password-one\nsecond — password-two'),/insert failed/);assert.equal(f.service.products()[0].stock,0);assert.equal(f.db.prepare('SELECT count(*) n FROM site_password_history').get().n,0);});
test('bulk inventory removal is website-scoped, requires confirmation, and protects live leases/history',t=>{
 const f=fixture(t);f.add('a');f.add('b');f.buy();assert.throws(()=>f.service.removeStock(f.product,{confirm:'wrong'}),/exact website name/);
 const other=f.service.saveProduct({name:'Other',url:'https://example.test',enabled:true,plans:[{key:'week',days:7,price:100}]});f.service.addStock(other,{username:'other',password:'other-secret'});
 const r=f.service.removeStock(f.product,{confirm:'Demo website'});assert.equal(r.removed,1);assert.equal(r.protected,1);assert.equal(f.service.accounts(1)[0].password,'secret-a');assert.equal(f.service.inventory(f.product).length,1);assert.equal(f.service.inventory(other).length,1);assert.equal(f.db.prepare('SELECT count(*) n FROM site_sales').get().n,1);
 f.advance(7*DAY);assert.equal(f.service.removeStock(f.product,{confirm:'Demo website'}).removed,1);assert.equal(f.service.accounts(1)[0].password,null);assert.equal(f.service.products(true).find(p=>p.id===f.product).counts.total,0);
});
test('website positions persist, include hidden sites, append new sites and never change stock',t=>{
 const f=fixture(t);f.add('a');const second=f.service.saveProduct({name:'Second',url:'https://example.test',enabled:true,plans:[{key:'week',days:7,price:100}]});const hidden=f.service.saveProduct({name:'Hidden',url:'https://example.test',enabled:false,plans:[{key:'week',days:7,price:100}]});
 assert.deepEqual(f.service.products(true).map(p=>p.id),[f.product,second,hidden]);f.service.moveProduct(second,'up');assert.deepEqual(f.service.products().map(p=>p.id),[second,f.product]);f.service.moveProduct(second,'up');f.service.moveProduct(hidden,'up');assert.deepEqual(f.service.products(true).map(p=>p.id),[second,hidden,f.product]);assert.equal(f.service.inventory(f.product).length,1);
 assert.throws(()=>f.service.moveProduct(999,'up'),/not found/);assert.throws(()=>f.service.moveProduct(second,'left'),/up or down/);
 const reopened=createStore(f.db,f.key);assert.deepEqual(reopened.products(true).map(p=>p.id),[second,hidden,f.product]);f.service.moveProduct(second,'down');assert.deepEqual(f.service.products(true).map(p=>p.id),[hidden,second,f.product]);
});
test('ordering migration preserves the old newest-first catalog only on first startup',t=>{
 const db=new Database(':memory:');t.after(()=>db.close());db.exec("CREATE TABLE site_products(id INTEGER PRIMARY KEY,name TEXT NOT NULL,image TEXT NOT NULL DEFAULT '',url TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 0,plans TEXT NOT NULL);INSERT INTO site_products VALUES(1,'A','','https://example.test',1,'[]'),(2,'B','','https://example.test',1,'[]');");const {schema}=require('../utils/site-store');schema(db);assert.deepEqual(db.prepare('SELECT id FROM site_products ORDER BY sort_rank').all().map(r=>r.id),[2,1]);db.exec('UPDATE site_products SET sort_rank=10 WHERE id=2');schema(db);assert.deepEqual(db.prepare('SELECT id FROM site_products ORDER BY sort_rank').all().map(r=>r.id),[1,2]);
});
