'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),Database=require('better-sqlite3'),express=require('express'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
test('website API enforces admin/customer boundaries, returns private credentials only to current owner, and rejects unsafe URLs',async t=>{
 const db=new Database(':memory:');db.exec("CREATE TABLE users(id INTEGER PRIMARY KEY,coins INTEGER,telegram_id TEXT);INSERT INTO users VALUES(1,10000,NULL),(2,10000,NULL);CREATE TABLE settings(key TEXT PRIMARY KEY,value TEXT);");
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'site-api-'));const app=express();app.use(express.json());app.use((req,res,next)=>{req.session={userId:Number(req.headers['x-user'])||null,isAdmin:req.headers['x-admin']==='yes'};next();});const auth=(req,res,next)=>req.session.userId||req.session.isAdmin?next():res.sendStatus(401),admin=(req,res,next)=>req.session.isAdmin?next():res.sendStatus(403);
 const store=require('../utils/site-store-routes')(app,db,auth,admin,(req,res,next)=>next(),{keyFile:path.join(dir,'site-stock.key')});
 const server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});t.after(async()=>{await new Promise(r=>server.close(r));db.close();fs.rmSync(dir,{recursive:true,force:true});});const base=`http://127.0.0.1:${server.address().port}`;
 const request=(p,body,headers={})=>fetch(base+p,{method:body?'POST':'GET',headers:{'content-type':'application/json',...headers},...(body?{body:JSON.stringify(body)}:{})});
 assert.equal((await request('/api/admin/site-store')).status,403);assert.equal((await request('/api/me/site-accounts')).status,401);assert.equal((await request('/api/me/site-accounts',null,{'x-admin':'yes'})).status,403);
 const product={name:'Example',url:'https://example.test',image:'',enabled:true,plans:[{key:'week',days:7,price:100}]};assert.equal((await request('/api/admin/site-store/products',product,{'x-user':'1'})).status,403);assert.equal((await request('/api/admin/site-store/products',{...product,url:'javascript:alert(1)'},{'x-admin':'yes'})).status,400);
 const p=await (await request('/api/admin/site-store/products',product,{'x-admin':'yes'})).json();await request(`/api/admin/site-store/products/${p.id}/stock`,{username:'private-user',password:'private-password'},{'x-admin':'yes'});
 const catalog=await (await request('/api/site-store')).json();assert.doesNotMatch(JSON.stringify(catalog),/private-|cipher|url/);
 const body={product_id:p.id,plan_key:'week',quantity:1,request_key:crypto.randomUUID(),expected_total:100,expected_same_account:false};assert.equal((await request('/api/site-store/purchase',body,{'x-admin':'yes'})).status,403);assert.equal((await request('/api/site-store/purchase',body,{'x-user':'1'})).status,200);
 const own=await request('/api/me/site-accounts',null,{'x-user':'1'});assert.equal(own.headers.get('cache-control'),'no-store');assert.equal((await own.json())[0].password,'private-password');assert.deepEqual(await (await request('/api/me/site-accounts',null,{'x-user':'2'})).json(),[]);
 assert.equal((await request('/api/site-store/quote',{...body,renew_id:1},{'x-user':'2'})).status,400);
 assert.equal((await request(`/api/admin/site-store/products/${p.id}/remove-stock`,{confirm:'Example'},{'x-user':'1'})).status,403);const removal=await(await request(`/api/admin/site-store/products/${p.id}/remove-stock`,{confirm:'Example'},{'x-admin':'yes'})).json();assert.equal(removal.protected,1);assert.equal(removal.removed,0);
 assert.equal((await request(`/api/admin/site-store/products/${p.id}/move`,{direction:'up'},{'x-user':'1'})).status,403);assert.equal((await request(`/api/admin/site-store/products/${p.id}/move`,{direction:'up'},{'x-admin':'yes'})).status,200);
 assert.doesNotMatch(JSON.stringify(store.inventory(p.id)),/private-password|cipher/);assert.equal(fs.statSync(path.join(dir,'site-stock.key')).mode&0o777,0o600);
});
