'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),DB=require('better-sqlite3'),crypto=require('crypto');
const {createStore,DAY}=require('../utils/site-store');
const {createStockAlerts}=require('../utils/stock-alerts');
function fixture(t){const db=new DB(':memory:');t.after(()=>db.close());db.exec("CREATE TABLE settings(key TEXT PRIMARY KEY,value TEXT);INSERT INTO settings VALUES('site_url','https://panel.test');CREATE TABLE users(id INTEGER PRIMARY KEY,telegram_id TEXT,coins INTEGER);INSERT INTO users VALUES(1,'111',10000),(2,'222',10000),(3,'111',10000),(4,'',0);");let time=Date.parse('2026-10-08T00:00:00Z');const store=createStore(db,crypto.randomBytes(32),{now:()=>time});const id=store.saveProduct({name:'MAAN <WIN>',url:'https://purchased.test',enabled:true,plans:[{key:'week',days:7,price:100}]});const sent=[];let fault=null;
 const options={now:()=>time,delay:async()=>{},send:async(chat,html,rows)=>{if(fault)throw fault;sent.push({chat,html,rows});return {message_id:sent.length};}};const worker=createStockAlerts(db,options);
 return {db,store,id,sent,options,worker,advance:ms=>time+=ms,fail:e=>fault=e,events:()=>db.prepare('SELECT * FROM stock_alerts').all()};}
test('bulk add queues one premium credential-free alert, deduplicates audience and links to catalog',async t=>{const f=fixture(t);f.store.addBulkStock(f.id,'01. private-user — private-password\n02. second-user — second-password');assert.equal(f.events().length,1);assert.equal(f.events()[0].added,2);assert.equal(f.events()[0].available,2);assert.equal(f.sent.length,0);await f.worker.tick();assert.equal(f.sent.length,2);assert.match(f.sent[0].html,/<b>.*2 accounts added/);assert.match(f.sent[0].html,/MAAN &lt;WIN&gt;/);assert.doesNotMatch(JSON.stringify(f.sent),/private-user|private-password|second-user|second-password/);assert.match(f.sent[0].rows[0][0].web_app.url,/tab=fakesite/);await f.worker.tick();await createStockAlerts(f.db,f.options).tick();assert.equal(f.sent.length,2);});
test('failed duplicate/invalid/rolled-back imports enqueue nothing',t=>{const f=fixture(t);assert.throws(()=>f.store.addBulkStock(f.id,'a — valid-password\na — other-password'));assert.equal(f.events().length,0);f.db.exec("CREATE TRIGGER fail_second BEFORE INSERT ON site_stock WHEN NEW.username='second' BEGIN SELECT RAISE(ABORT,'failure'); END;");assert.throws(()=>f.store.addBulkStock(f.id,'first — password-one\nsecond — password-two'));assert.equal(f.events().length,0);assert.equal(f.store.products()[0].stock,0);f.store.addStock(f.id,{username:'single',password:'single-password'});assert.throws(()=>f.store.addStock(f.id,{username:'single',password:'single-password'}));assert.equal(f.events().length,1);});
test('hidden products do not queue; disabling or selling out before delivery cancels alerts',async t=>{const f=fixture(t);f.db.prepare('UPDATE site_products SET enabled=0 WHERE id=?').run(f.id);f.store.addStock(f.id,{username:'a',password:'password-a'});assert.equal(f.events().length,0);f.db.prepare('UPDATE site_products SET enabled=1 WHERE id=?').run(f.id);f.store.addStock(f.id,{username:'b',password:'password-b'});f.db.exec("UPDATE site_stock SET state='archived'");await f.worker.tick();assert.equal(f.sent.length,0);assert.equal(f.events()[0].state,'cancelled');});
test('rate limits retry pending recipients, unknown delivery never blindly resends',async t=>{const f=fixture(t);f.store.addStock(f.id,{username:'a',password:'password-a'});f.fail({response:{body:{error_code:429,parameters:{retry_after:30}}}});await f.worker.tick();assert.equal(f.db.prepare("SELECT count(*) n FROM stock_alert_recipients WHERE state='pending'").get().n,2);f.fail(null);await f.worker.tick();assert.equal(f.sent.length,0);f.advance(31001);await f.worker.tick();assert.equal(f.sent.length,2);
 f.store.addStock(f.id,{username:'b',password:'password-b'});f.fail(Error('timeout'));await f.worker.tick();assert.equal(f.db.prepare("SELECT count(*) n FROM stock_alert_recipients WHERE state='unknown'").get().n,2);f.fail(null);await createStockAlerts(f.db,f.options).tick();assert.equal(f.sent.length,2);});
test('password-rotated restock creates one new alert, purchases do not',t=>{const f=fixture(t);f.store.addStock(f.id,{username:'a',password:'password-a'});const q=f.store.quote(1,{product_id:f.id,plan_key:'week'});f.store.purchase(1,{product_id:f.id,plan_key:'week',expected_total:q.total,expected_same_account:q.same_account,request_key:crypto.randomUUID()});assert.equal(f.events().length,1);f.advance(8*DAY);f.store.inventory(f.id);f.store.restock(1,{password:'changed-password',confirmed:true});assert.equal(f.events().length,2);assert.equal(f.events()[1].added,1);});
test('bot-unavailable cooldown covers newly added batches, blocked recipients are terminal',async t=>{const f=fixture(t);f.store.addStock(f.id,{username:'a',password:'password-a'});f.fail({code:'BOT_NOT_READY'});await f.worker.tick();f.store.addStock(f.id,{username:'b',password:'password-b'});f.fail(null);await f.worker.tick();assert.equal(f.sent.length,0);f.advance(300001);f.fail({response:{body:{error_code:403}}});await f.worker.tick();assert.equal(f.db.prepare("SELECT count(*) n FROM stock_alert_recipients WHERE state='blocked'").get().n,4);f.fail(null);await createStockAlerts(f.db,f.options).tick();assert.equal(f.sent.length,0);});
