const {test}=require('node:test'),assert=require('node:assert/strict'),DB=require('better-sqlite3');
const {createNotifications}=require('../utils/welcome-notifications');
const DAY=86400000;
function setup(t){const db=new DB(':memory:');t.after(()=>db.close());let time=Date.parse('2026-10-07T00:00:00Z'),expiry=time+3*DAY,success=true;
 db.exec("CREATE TABLE settings(key TEXT,value TEXT);INSERT INTO settings VALUES('site_url','https://panel.test');CREATE TABLE users(id INTEGER,telegram_id TEXT);INSERT INTO users VALUES(1,'123');CREATE TABLE welcome_orders(id INTEGER,user_id INTEGER,kind TEXT,refunded INTEGER,status TEXT,remote_id TEXT,expires_at TEXT,bot_name TEXT,bot_username TEXT);");
 const stamp=()=>new Date(expiry).toISOString();db.prepare('INSERT INTO welcome_orders VALUES(1,1,\'deploy\',0,\'active\',\'remote1\',?,\'Demo <bot>\',\'demo_bot\')').run(stamp());
 const sent=[];const options={now:()=>time,notify:async(...args)=>{if(!success)return null;sent.push(args);return {message_id:sent.length};}};
 const n=createNotifications(db,options);const fleet=()=>({subscription_notice_owner:'builder',bots:[{remote_id:'remote1',expires_at:stamp(),status:time>=expiry?'expired':'active'}]});
 return {db,sent,options,n,fleet,advance:days=>time+=days*DAY,offline:()=>success=false,online:()=>success=true,renew:()=>{expiry+=30*DAY;db.prepare('UPDATE welcome_orders SET expires_at=?').run(stamp());}};
}
test('builder delivers 3d, 1d and expiry once each with safe direct renewal link',async t=>{const f=setup(t);await f.n.tick(f.fleet());await f.n.tick(f.fleet());assert.equal(f.sent.length,1);assert.equal(f.sent[0][0],'123');assert.match(f.sent[0][1],/Demo &lt;bot&gt;/);assert.match(f.sent[0][2].inline_keyboard[0][0].web_app.url,/tab=deploy/);assert.doesNotMatch(f.sent[0][1],/panel.test|token|password/);f.advance(2);await f.n.tick(f.fleet());f.advance(1);await f.n.tick(f.fleet());assert.equal(f.sent.length,3);const reopened=createNotifications(f.db,f.options);await reopened.tick(f.fleet());assert.equal(f.sent.length,3);});
test('old runtime, stale expiry, refunded orders and missing owners cannot trigger delivery',async t=>{const f=setup(t);await f.n.tick({bots:f.fleet().bots});assert.equal(f.sent.length,0);const stale=f.fleet();f.renew();await f.n.tick(stale);assert.equal(f.sent.length,0);f.advance(30);f.db.exec('UPDATE welcome_orders SET refunded=1');await f.n.tick(f.fleet());assert.equal(f.sent.length,0);});
test('offline sends retry, renewal cancels old period, and new period gets independent reminders',async t=>{const f=setup(t);f.offline();await f.n.tick(f.fleet());assert.equal(f.sent.length,0);f.online();await f.n.tick(f.fleet());assert.equal(f.sent.length,0);f.advance(0.01);await f.n.tick(f.fleet());assert.equal(f.sent.length,1);f.renew();f.advance(2);await f.n.tick(f.fleet());assert.equal(f.sent.length,1);f.advance(28);await f.n.tick(f.fleet());assert.equal(f.sent.length,2);});
test('late first contact sends only current phase, overlapping ticks do not duplicate',async t=>{const f=setup(t);f.advance(2.5);await Promise.all([f.n.tick(f.fleet()),f.n.tick(f.fleet())]);assert.equal(f.sent.length,1);assert.match(f.sent[0][1],/24 hours/);});
test('migration honors already-sent manager reminders for the same validity period',async t=>{const f=setup(t),fleet=f.fleet();fleet.bots[0].legacy_reminders={'3d':true};await f.n.tick(fleet);await f.n.tick(f.fleet());assert.equal(f.sent.length,0);f.advance(2);await f.n.tick(f.fleet());assert.equal(f.sent.length,1);});
