// Synthetic preview only: PREVIEW_AUTO_USDT=1 node scripts/preview-deposits.mjs
const assert=require('node:assert/strict'),path=require('node:path');
const tools=require('node:module').createRequire(path.resolve(process.env.BROWSER_TOOLS_DIR||'/home/user/browser-tools','package.json'));
const {chromium}=tools('playwright-core'),c=tools('@sparticuz/chromium').default;
(async()=>{const browser=await chromium.launch({executablePath:await c.executablePath(),args:c.args.filter(a=>a!=='--single-process'),headless:true});try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://telegram.org/**',r=>r.fulfill({body:'',contentType:'application/javascript'}));await page.request.post('http://127.0.0.1:5173/api/__preview_reset');await page.goto('http://127.0.0.1:5173/#wallet');await page.getByRole('button',{name:/USDT TRC20/}).click();
 const response=page.waitForResponse(r=>r.url().endsWith('/api/deposits/quote'));await page.getByRole('button',{name:'Continue with USDT TRC20',exact:true}).click();const q=await (await response).json();assert(q.automatic);assert.equal(q.amount,'10.000001');await page.getByText('Waiting for confirmed payment',{exact:true}).waitFor();assert.equal(await page.getByLabel('Payment screenshot').count(),0);await page.getByRole('button',{name:'Late or different amount? Submit proof'}).click();await page.getByLabel('Actual USDT amount sent').fill('5');await page.getByRole('button',{name:'Back to payment status'}).click();assert.equal(await page.getByLabel('Payment screenshot').count(),0);
 await page.getByRole('button',{name:'Close · finish later'}).click();await page.request.post('http://127.0.0.1:5173/api/__preview_auto_event',{data:{id:q.id}});await page.locator('.deposit-balance strong').filter({hasText:'1,202'}).waitFor({timeout:20000});await page.getByRole('button',{name:'Resume',exact:true}).click();await page.getByText('Payment received',{exact:true}).waitFor();assert.equal(await page.locator('.deposit-qr img').count(),0);assert.equal(await page.getByLabel('Payment screenshot').count(),0);await page.getByRole('button',{name:'Close · finish later'}).click();
 await page.getByRole('button',{name:/USDT BEP20/}).click();await page.getByRole('button',{name:'Continue with USDT BEP20',exact:true}).click();await page.getByText('Waiting for confirmed payment',{exact:true}).waitFor();await page.getByRole('button',{name:'Late or different amount? Submit proof'}).click();await page.getByLabel('Actual USDT amount sent').fill('5');await page.getByLabel('Transaction hash (TXID)').fill('e'.repeat(64));await page.locator('.deposit-qr img').waitFor();const image=await page.locator('.deposit-qr img').getAttribute('src');await page.getByLabel('Payment screenshot').setInputFiles({name:'proof.png',mimeType:'image/png',buffer:Buffer.from(image.split(',')[1],'base64')});await page.getByLabel('Note (optional)').fill('Different amount sent');await page.getByRole('button',{name:'Submit payment proof',exact:true}).click();await page.getByText('₹475 wallet credit',{exact:true}).waitFor();assert.match(await page.locator('.deposit-balance').innerText(),/1,202/);
 assert.deepEqual(errors,[]);console.log('PASS: TRC20 auto invoice, exact amount, timer, hidden proof toggle, server credit while closed, paid receipt, BEP20 different-amount review without wallet credit.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
