// Run against: node scripts/preview-deposits.mjs (synthetic payments only).
const assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs');
const tools=require('node:module').createRequire(path.resolve(process.env.BROWSER_TOOLS_DIR||'/home/user/browser-tools','package.json'));
const {chromium}=tools('playwright-core'),c=tools('@sparticuz/chromium').default,decode=tools('jsqr'),{PNG}=tools('pngjs');
(async()=>{const browser=await chromium.launch({executablePath:await c.executablePath(),args:c.args.filter(a=>a!=='--single-process'),headless:true});try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://telegram.org/**',r=>r.fulfill({body:'',contentType:'application/javascript'}));
 await page.request.post('http://127.0.0.1:5173/api/__preview_reset');await page.goto('http://127.0.0.1:5173/');await page.locator('.wallet-fund-btn').waitFor();assert.notEqual(await page.locator('.fund-action-hint>svg').evaluate(e=>getComputedStyle(e).animationName),'none');await page.locator('.wallet-fund-btn').click();await page.getByText('Choose your payment route').waitFor();
 const screenshot=async name=>{if(process.env.SCREENSHOT_DIR){fs.mkdirSync(process.env.SCREENSHOT_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.SCREENSHOT_DIR,name),fullPage:false,animations:'disabled'});}};
 await screenshot('deposit-upi.png');
 for(const width of [320,390,768]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await page.locator('.deposit-methods button').count(),3);}
 await page.setViewportSize({width:390,height:844});await page.getByLabel('Custom deposit amount').fill('1.5');assert(await page.getByRole('button',{name:'Continue with UPI',exact:true}).isDisabled());await page.getByLabel('Custom deposit amount').fill('333');await page.getByRole('button',{name:'Continue with UPI',exact:true}).click();await page.locator('.deposit-qr img').waitFor();
 const qr=async()=>{const data=await page.locator('.deposit-qr img').getAttribute('src'),png=PNG.sync.read(Buffer.from(data.split(',')[1],'base64'));const decoded=decode(new Uint8ClampedArray(png.data),png.width,png.height);assert(decoded,'QR must decode');return decoded.data;};
 let payload=new URL(await qr());assert.equal(payload.searchParams.get('am'),'333.00');assert.equal(payload.searchParams.get('pa'),'demo@bank');assert.equal(payload.searchParams.get('cu'),'INR');assert.doesNotMatch(await page.getByRole('dialog').innerText(),/admin|manual verification/i);assert.match(await page.getByRole('dialog').innerText(),/Add payment details/);assert.equal(await page.locator('.deposit-methods .usdt-token').count(),2);await screenshot('deposit-upi-qr.png');
 await page.evaluate(()=>{window.copied=[];Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async v=>window.copied.push(v),readText:async()=> '123456789012'}});});await page.getByRole('button',{name:'Copy UPI ID',exact:true}).click();assert.deepEqual(await page.evaluate(()=>window.copied),['demo@bank']);
 await page.getByRole('button',{name:'Close · finish later'}).click();await page.reload();await page.getByRole('button',{name:'Resume',exact:true}).click();await page.locator('.deposit-qr img').waitFor();assert.equal(new URL(await qr()).searchParams.get('am'),'333.00');await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{readText:async()=> '123456789012'}}));await page.getByRole('button',{name:'Paste payment reference'}).click();assert.equal(await page.getByLabel('12-digit UTR').inputValue(),'123456789012');
 await page.getByLabel('Payment screenshot').setInputFiles({name:'bad.txt',mimeType:'text/plain',buffer:Buffer.from('not an image')});assert.equal(await page.locator('.deposit-upload.has-file').count(),0);
await page.getByLabel('Payment screenshot').setInputFiles({name:'proof.png',mimeType:'image/png',buffer:Buffer.from((await page.locator('.deposit-qr img').getAttribute('src')).split(',')[1],'base64')});await page.getByAltText('Selected payment screenshot').waitFor();await page.getByRole('button',{name:'Remove screenshot'}).click();assert.equal(await page.getByLabel('Payment screenshot').evaluate(e=>e.files.length),0);assert.equal(await page.locator('.deposit-upload.has-file').count(),0);await page.getByLabel('Payment screenshot').setInputFiles({name:'proof.png',mimeType:'image/png',buffer:Buffer.from((await page.locator('.deposit-qr img').getAttribute('src')).split(',')[1],'base64')});await page.getByAltText('Selected payment screenshot').waitFor();assert.match(await page.locator('.deposit-upload').innerText(),/Screenshot attached/);await page.getByRole('button',{name:'Submit payment proof',exact:true}).scrollIntoViewIfNeeded();await screenshot('deposit-proof-refined.png');assert(await page.getByRole('button',{name:'Close',exact:true}).isVisible());const closeBox=await page.getByRole('button',{name:'Close',exact:true}).boundingBox();assert(closeBox.y>=0&&closeBox.y+closeBox.height<844);for(const width of [320,390]){await page.setViewportSize({width,height:844});assert.equal(await page.getByRole('dialog').evaluate(e=>e.scrollWidth>e.clientWidth),false);}await page.getByRole('button',{name:'Submit payment proof',exact:true}).click();await page.getByRole('dialog').waitFor({state:'detached'});await page.getByText('₹333 wallet credit',{exact:true}).waitFor();assert.match(await page.locator('.deposit-page').innerText(),/₹333 wallet credit/);assert.match(await page.locator('.deposit-balance').innerText(),/₹250/);
 await page.getByRole('button',{name:/USDT TRC20/}).click();await screenshot('deposit-usdt.png');await page.getByRole('button',{name:'Continue with USDT TRC20',exact:true}).click();await page.locator('.deposit-qr img').waitFor();assert.equal(await qr(),'T'+'A'.repeat(33));assert.match(await page.getByRole('dialog').innerText(),/Address-only QR/);assert.match(await page.getByRole('dialog').innerText(),/10.00 USDT/);await screenshot('deposit-usdt-qr.png');await page.getByRole('button',{name:'Close · finish later'}).click();
 await page.getByRole('button',{name:/USDT BEP20/}).click();await page.getByRole('button',{name:'Continue with USDT BEP20',exact:true}).click();await page.locator('.deposit-qr img').waitFor();assert.equal(await qr(),'0x'+'a'.repeat(40));await page.getByRole('button',{name:'Close · finish later'}).click();
 await page.route('**/api/settings/payment',r=>r.fulfill({json:{upi_id:'demo@bank'}}));await page.reload();await page.getByRole('button',{name:/USDT TRC20/}).click();assert(await page.getByRole('button',{name:'Continue with USDT TRC20',exact:true}).isDisabled());assert.match(await page.locator('.deposit-page').innerText(),/not available yet/);
 assert.deepEqual(errors,[]);console.log('PASS: mobile sizes, animated fund CTA, genuine amount QR decoded, both USDT QR payloads, disabled networks, copy, saved resume, proof submission, no automatic credit or browser errors.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
