// Start scripts/preview-resellers.mjs first. This exercises only synthetic data.
const assert=require('node:assert/strict'),path=require('node:path');
const tools=require('node:module').createRequire(path.resolve(process.env.BROWSER_TOOLS_DIR||'/home/user/browser-tools','package.json'));
const {chromium}=tools('playwright-core'),c=tools('@sparticuz/chromium').default;
(async()=>{const browser=await chromium.launch({executablePath:await c.executablePath(),args:c.args.filter(a=>a!=='--single-process'),headless:true});try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[],native=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',async d=>{native.push(d.message());await d.dismiss();});await page.route('https://telegram.org/**',r=>r.fulfill({body:'',contentType:'application/javascript'}));
 const base='http://127.0.0.1:5174';await page.request.post(base+'/api/__preview_reseller_reset');
 await page.goto(base+'/demo/admin');await page.getByRole('button',{name:'menu',exact:true}).click();await page.getByRole('button',{name:/Resellers Partner rates/}).click();
 await page.getByRole('heading',{name:'Resellers',exact:true}).waitFor();await page.getByRole('button',{name:'View report for Demo Partner'}).waitFor();
 assert.equal(await page.getByRole('heading',{name:'Service performance',exact:true}).count(),0,'directory must not show unselected reports');
 await page.screenshot({path:'/home/user/reseller-v2-directory.png'});
 await page.getByRole('button',{name:'View report for Demo Partner'}).click();await page.getByRole('heading',{name:'Service performance',exact:true}).waitFor();
 assert.match(await page.locator('.rs-service-card.apk').innerText(),/Lifetime\n2\nToday\n2/);assert.match(await page.locator('.rs-service-card.site').innerText(),/Lifetime\n2/);
 await page.getByRole('button',{name:'Edit rates'}).click();let dialog=page.getByRole('dialog');await dialog.getByLabel('APK OFF %').fill('99');await dialog.getByRole('button',{name:'Review settings'}).click();await dialog.getByRole('alert').filter({hasText:'between 0 and 95'}).waitFor();
 await dialog.getByLabel('APK OFF %').fill('35');await dialog.getByRole('button',{name:'Review settings'}).click();await page.getByRole('dialog',{name:'Confirm reseller settings'}).waitFor();await page.screenshot({path:'/home/user/reseller-v2-confirm.png'});
 await page.getByRole('button',{name:'Confirm & save'}).click();await page.getByRole('dialog',{name:'Reseller saved'}).waitFor();await page.getByRole('button',{name:'Done',exact:true}).click();
 let data=await(await page.request.get(base+'/api/admin/resellers/42')).json();assert.equal(data.profile.apk_percent,35);assert.equal(data.orders.find(o=>o.service==='apk').paid_paise,90860);
 // Cancel does not mutate access. Confirm removal archives access, not funds or history.
 await page.getByRole('button',{name:'Remove',exact:true}).click();await page.getByRole('button',{name:'Cancel',exact:true}).click();assert.equal((await(await page.request.get(base+'/api/admin/resellers/42')).json()).profile.status,'active');
 await page.getByRole('button',{name:'Remove',exact:true}).click();await page.getByRole('button',{name:'Remove reseller',exact:true}).click();await page.getByRole('dialog',{name:'Reseller removed'}).waitFor();await page.getByRole('button',{name:'Done',exact:true}).click();await page.getByRole('heading',{name:'No resellers here yet'}).waitFor();
 await page.getByLabel('Filter status').selectOption('removed');await page.getByRole('button',{name:'View report for Demo Partner'}).click();await page.getByRole('button',{name:'Restore reseller'}).click();await page.getByRole('button',{name:'Review settings'}).click();await page.getByRole('button',{name:'Confirm & save'}).click();await page.getByRole('dialog',{name:'Reseller saved'}).waitFor();await page.getByRole('button',{name:'Done',exact:true}).click();
 data=await(await page.request.get(base+'/api/admin/resellers/42')).json();assert.equal(data.profile.removed_at,null);assert.equal(data.user.coins,4250.75);assert.equal(data.lifetime.orders,3);
 await page.getByRole('tab',{name:'Orders & payments'}).click();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export CSV'}).click();assert.equal((await download).suggestedFilename(),'reseller-orders.csv');
 await page.getByRole('button',{name:'All resellers',exact:true}).click();await page.getByLabel('Filter status').selectOption('all');await page.getByRole('button',{name:'Add reseller',exact:true}).click();await page.getByPlaceholder('Username, user ID or Telegram ID').fill('New Partner');await page.getByRole('button',{name:/New Partner/}).click();await page.getByRole('button',{name:'Review settings'}).click();await page.getByRole('button',{name:'Confirm & save'}).click();await page.getByRole('dialog',{name:'Reseller saved'}).waitFor();await page.getByRole('button',{name:'Done',exact:true}).click();await page.getByRole('button',{name:'View report for New Partner'}).waitFor();
 assert.equal((await(await page.request.get(base+'/api/admin/resellers?summary=1')).json()).total,2);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'mobile overflow');
 await page.getByRole('button',{name:'View report for Demo Partner'}).click();await page.getByRole('heading',{name:'Service performance',exact:true}).waitFor();await page.setViewportSize({width:1365,height:900});await page.screenshot({path:'/home/user/reseller-v2-report.png'});
 await page.goto(base+'/demo/customer');await page.getByRole('heading',{name:'Service performance',exact:true}).waitFor();await page.locator('.load-mark').waitFor({state:'detached'});assert.match(await page.locator('.rs-service-card.apk').innerText(),/Lifetime\n2/);
 assert.deepEqual(native,[],'must never use native dialogs');assert.deepEqual(errors,[]);console.log('PASS: list-first navigation, isolated partner report, real/fake APK and site quantities, custom validation/confirm/success popups, cancel/remove/restore safety, add reseller, preserved wallet/history, CSV, mobile layout, customer breakdown. No native dialogs.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
