const path=require('node:path'),assert=require('node:assert/strict');
const tools=require('node:module').createRequire(path.resolve(process.env.BROWSER_TOOLS_DIR||'../browser-tools','package.json'));
const {chromium:p}=tools('playwright-core'),c=tools('@sparticuz/chromium').default;
(async()=>{const browser=await p.launch({executablePath:await c.executablePath(),args:[...c.args.filter(a=>a!=='--single-process'),'--disable-gpu'],headless:true});try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://telegram.org/**',r=>r.fulfill({body:'',contentType:'application/javascript'}));await page.request.post('http://127.0.0.1:5173/api/__preview_reset');await page.goto('http://127.0.0.1:5173/');await page.locator('.bottomnav button').filter({hasText:/Fake/i}).click();
 await page.locator('.site-product').first().waitFor();assert.equal(await page.locator('.site-product').count(),2);const boxes=await page.locator('.site-product').evaluateAll(es=>es.map(e=>({x:e.getBoundingClientRect().x,y:e.getBoundingClientRect().y})));assert.equal(boxes[0].y,boxes[1].y);assert.notEqual(boxes[0].x,boxes[1].x);
 if(process.env.SCREENSHOT_DIR){require('node:fs').mkdirSync(process.env.SCREENSHOT_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.SCREENSHOT_DIR,'website-catalog.png'),fullPage:true,animations:'disabled'});}
 assert(!/1 Year Premium/.test(await page.locator('body').innerText()));await page.locator('.site-product').first().getByRole('button',{name:'Buy now'}).click();assert.equal(await page.locator('.site-best').count(),1);assert.equal(await page.locator('.site-plan .savings-ribbon').count(),2);assert((await page.locator('.site-plan').first().boundingBox()).height<105);assert.equal(await page.getByRole('button',{name:'Decrease quantity'}).isDisabled(),true);await page.getByRole('button',{name:'Increase quantity'}).click();assert.equal(await page.getByLabel('Quantity',{exact:true}).innerText(),'2');await page.getByRole('button',{name:'Increase quantity'}).click();assert.equal(await page.getByRole('button',{name:'Increase quantity'}).isDisabled(),true);await page.getByRole('button',{name:'Decrease quantity'}).click();await page.getByRole('button',{name:'Decrease quantity'}).click();
 if(process.env.SCREENSHOT_DIR)await page.screenshot({path:path.join(process.env.SCREENSHOT_DIR,'website-plans.png'),fullPage:true,animations:'disabled'});
 await page.getByRole('button',{name:'Purchase',exact:true}).click();if(process.env.SCREENSHOT_DIR)await page.screenshot({path:path.join(process.env.SCREENSHOT_DIR,'purchase-result.png'),animations:'disabled'});await page.getByRole('button',{name:'View my accounts',exact:true}).click();await page.getByText('sample-2-1',{exact:true}).waitFor();await page.getByText('sample-password-1',{exact:true}).waitFor();

 const credential=page.locator('.site-credentials');const link=credential.locator('.credential-url');assert.match(await link.innerText(),/^https:\/\//);assert.equal(await link.getAttribute('href'),await link.innerText());
 await page.evaluate(()=>{window.copiedValues=[];Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async v=>window.copiedValues.push(v)}});});
 await page.getByRole('button',{name:/Copy account ID/}).click();await page.getByRole('button',{name:/Copy password/}).click();assert.deepEqual(await page.evaluate(()=>window.copiedValues),['sample-2-1','sample-password-1']);
 await page.goto('http://127.0.0.1:5173/?tab=fakesite&section=accounts#tgWebAppData=simulated');await page.getByText('sample-2-1',{exact:true}).waitFor();assert.equal(await page.locator('.site-grid').count(),0);
 await page.goto('http://127.0.0.1:5173/?tab=deploy#tgWebAppData=simulated');await page.locator('.welcome-product').waitFor();
 await page.goto('http://127.0.0.1:5173/#wallet');await page.getByText('Current balance',{exact:true}).waitFor();
 await page.goto('http://127.0.0.1:5173/#fakesite/accounts');await page.getByText('sample-2-1',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Select renewal plan'}).click();await page.getByRole('button',{name:/30 days plan/}).click();await page.getByText('Renewal par same login rahega.',{exact:false}).waitFor();await page.getByRole('button',{name:'Renew now'}).click();await page.getByRole('button',{name:'View my accounts',exact:true}).click();await page.getByText('sample-2-1',{exact:true}).waitFor();assert.equal(await page.locator('.site-credentials').count(),1);
 await page.request.post('http://127.0.0.1:5173/api/__site_expire');await page.reload();await page.locator('.bottomnav button').filter({hasText:/Fake/i}).click();await page.getByRole('button',{name:/My accounts/}).click();await page.getByText('Expired',{exact:true}).waitFor();assert.equal(await page.getByText('sample-password-1',{exact:true}).count(),0);await page.getByRole('button',{name:'Select renewal plan'}).click();await page.getByRole('button',{name:'Renew now'}).click();await page.getByRole('button',{name:'View my accounts',exact:true}).click();await page.getByText('sample-2-2',{exact:true}).waitFor();await page.getByText('sample-password-2',{exact:true}).waitFor();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.locator('.bottomnav button').filter({hasText:'Orders'}).click();await page.getByRole('button',{name:'Login details / renew'}).first().click();await page.getByText('sample-2-2',{exact:true}).waitFor();
 await page.goto('http://127.0.0.1:5173/admin');await page.getByRole('button',{name:'menu',exact:true}).click();await page.getByRole('button',{name:/Fake Websites/}).first().click();await page.getByText('Website store',{exact:true}).waitFor();await page.locator('.admin-selection-card').filter({hasText:'Demo Purple Website'}).click();await page.getByText('sample-2-1 · expired',{exact:true}).waitFor();await page.getByLabel('Account ID',{exact:true}).fill('manual-1');await page.getByLabel('Account password',{exact:true}).fill('new-test-password');await page.getByRole('button',{name:'Add stock',exact:true}).click();await page.getByText('manual-1 · available',{exact:true}).waitFor();
 await page.getByPlaceholder('New password after changing on website').fill('rotated-password');await page.getByLabel('I disabled old access and changed the password on the website.').check();await page.getByRole('button',{name:'Return to available stock'}).click();await page.getByText('sample-2-1 · available',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Delete stock in bulk'}).click();const removal=page.getByRole('dialog');await removal.getByLabel('Type the website name to confirm').fill('wrong');assert.equal(await removal.getByRole('button',{name:'Confirm removal'}).isDisabled(),true);await removal.getByLabel('Type the website name to confirm').fill('Demo Purple Website');await removal.getByRole('button',{name:'Confirm removal'}).click();await page.getByText('sample-2-2 · assigned',{exact:true}).waitFor();await page.getByText('manual-1 · available',{exact:true}).waitFor({state:'detached'});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.route('**/api/site-store',async route=>{const r=await route.fetch();const products=await r.json();await route.fulfill({response:r,json:products.slice(0,1)});});await page.goto('http://127.0.0.1:5173/');await page.locator('.bottomnav button').filter({hasText:/Fake/i}).click();await page.locator('.site-grid').waitFor();for(const width of [320,390]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert((await page.locator('.site-product').boundingBox()).width<(await page.locator('.site-grid').boundingBox()).width*.6);}if(process.env.SCREENSHOT_DIR)await page.screenshot({path:path.join(process.env.SCREENSHOT_DIR,'website-single.png'),fullPage:true,animations:'disabled'});assert.deepEqual(errors,[]);console.log('PASS: two-column mobile catalog, checkout, credential delivery, same-account renewal, expired replacement, admin stock/restock, no overflow or runtime errors.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
