const path=require('node:path'),assert=require('node:assert/strict'),fs=require('node:fs');
const tools=require('node:module').createRequire(path.resolve(process.env.BROWSER_TOOLS_DIR||'../browser-tools','package.json'));
const {chromium:p}=tools('playwright-core'),c=tools('@sparticuz/chromium').default;
(async()=>{const browser=await p.launch({executablePath:await c.executablePath(),args:[...c.args.filter(a=>a!=='--single-process'),'--disable-gpu'],headless:true});try{
 const page=await browser.newPage({viewport:{width:390,height:844}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://telegram.org/**',r=>r.fulfill({body:'',contentType:'application/javascript'}));await page.request.post('http://127.0.0.1:5173/api/__preview_reset');await page.goto('http://127.0.0.1:5173/');await page.locator('.premium-wallet').waitFor();assert.equal(await page.locator('.deploy-spotlight').count(),0);await page.locator('.load-mark').waitFor({state:'hidden'});
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`overflow at ${width}`);}
 await page.setViewportSize({width:390,height:844});if(process.env.SCREENSHOT_DIR){fs.mkdirSync(process.env.SCREENSHOT_DIR,{recursive:true});await page.screenshot({path:path.join(process.env.SCREENSHOT_DIR,'premium-home.png'),animations:'disabled'});}
 assert.equal(await page.locator('.bottomnav svg mask,.bottomnav svg [mask],.bottomnav svg defs').count(),0,'navigation icons must not depend on shared SVG mask IDs');assert.equal(await page.locator('.bottomnav .animated-bot rect').count(),1,'Deploy uses a robot body');assert.equal(await page.locator('.bottomnav .animated-globe ellipse').count(),1,'Website uses globe meridians');assert((await page.locator('.premium-wallet').boundingBox()).height<160);await page.locator('.bottomnav button').filter({hasText:'Deploy Bot'}).click();await page.locator('.welcome-product').waitFor();await page.locator('.bottomnav button').filter({hasText:'Home'}).click();await page.getByRole('button',{name:/Add Fund/i}).click();await page.getByText('Current balance',{exact:true}).waitFor();await page.locator('.bottomnav button').filter({hasText:'Hacks'}).click();await page.getByText('Available Hacks',{exact:true}).waitFor();await page.getByPlaceholder('Search hacks…').fill('test');assert.equal(await page.locator('.bottomnav').getByText('Templates',{exact:true}).count(),0);
 await page.emulateMedia({reducedMotion:'reduce'});await page.locator('.bottomnav button').filter({hasText:'Home'}).click();assert.equal(await page.locator('.bottomnav button svg').first().evaluate(e=>getComputedStyle(e).animationName),'none');assert.deepEqual(errors,[]);console.log('PASS: premium Home CTAs, Hacks navigation/search, 320–1440px layout and reduced-motion support.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
