// Requires scripts/preview-telegram-access.mjs; never uses production credentials.
const assert=require('node:assert/strict'),path=require('node:path'),crypto=require('crypto');
const tools=require('node:module').createRequire(path.resolve(process.env.BROWSER_TOOLS_DIR||'/home/user/browser-tools','package.json'));
const {chromium}=tools('playwright-core'),c=tools('@sparticuz/chromium').default;
const base='http://127.0.0.1:5180';
function proof(){const p=new URLSearchParams({auth_date:String(Math.floor(Date.now()/1000)),user:JSON.stringify({id:42,first_name:'Demo'}),query_id:'browser-test'});const key=crypto.createHmac('sha256','WebAppData').update('123456789:test-only-bot-secret').digest();p.set('hash',crypto.createHmac('sha256',key).update([...p.keys()].sort().map(k=>`${k}=${p.get(k)}`).join('\n')).digest('hex'));return p.toString();}
(async()=>{const browser=await chromium.launch({executablePath:await c.executablePath(),args:c.args.filter(x=>!['--single-process','--disable-web-security','--disable-site-isolation-trials','--allow-running-insecure-content'].includes(x)),headless:true});try{
 const context=await browser.newContext({viewport:{width:390,height:844}});await context.route('https://telegram.org/**',r=>r.fulfill({body:'',contentType:'application/javascript'}));
 const page=await context.newPage(),requests=[],errors=[];page.on('request',r=>requests.push(r.url()));page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/?tab=templates#templates');await page.getByRole('heading',{name:'Open inside Telegram.'}).waitFor();assert.equal(await page.getByRole('link',{name:/Open Telegram bot/}).getAttribute('href'),'https://t.me/TestAccessBot');assert(!requests.some(u=>u.endsWith('/api/designs')));assert(!requests.some(u=>u.endsWith('/src/main.jsx')));await page.screenshot({path:'/home/user/telegram-access-mobile.png'});
 assert.equal((await page.request.get(base+'/api/designs')).status(),403);assert.equal((await page.request.get(base+'/api/settings/payment')).status(),403);
 // A fake client object / Telegram-looking browser cannot unlock the panel.
 const fake=await context.newPage();await fake.addInitScript(()=>{window.Telegram={WebApp:{initData:'auth_date=123&user=%7B%22id%22%3A42%7D&hash=fake',initDataUnsafe:{user:{id:42}}}};});await fake.goto(base+'/');await fake.getByText(/Telegram access could not be verified/).waitFor();assert.equal(await fake.locator('.app-shell').count(),0);
 // Correctly signed fixture launch opens a real frontend using the middleware.
 const verified=await context.newPage();let authRequests=0;verified.on('request',r=>{if(r.url().endsWith('/api/auth/telegram-webapp'))authRequests++;});verified.on('pageerror',e=>errors.push(e.message));await verified.addInitScript(data=>{AbortSignal.timeout=undefined;window.Telegram={WebApp:{initData:data,initDataUnsafe:{user:{id:42}},ready(){},expand(){},setHeaderColor(){},setBackgroundColor(){},disableVerticalSwipes(){}}};},proof());await verified.goto(base+'/?tab=templates#templates');await verified.getByRole('heading',{name:'Private demo design',exact:true}).waitFor();await verified.locator('.load-mark').waitFor({state:'detached'});assert.equal(await verified.locator('.tg-access-page').count(),0);assert.equal(authRequests,1,'bootstrap must not duplicate Telegram authentication');
 assert.equal((await verified.request.get(base+'/api/designs')).status(),403,'even a valid cookie alone is insufficient for catalog API');
 assert(!errors.length,'signed launch must work even without AbortSignal.timeout');
 const copied=await context.newPage();await copied.goto(base+'/?tab=wallet');await copied.getByRole('heading',{name:'Open inside Telegram.'}).waitFor();assert.equal(await copied.locator('.app-shell').count(),0);
 // Expiry screen does not retry old initData or reveal the panel.
 await verified.goto(base+'/?telegram_access=expired');await verified.getByText(/Your session ended/).waitFor();
 const admin=await context.newPage();await admin.goto(base+'/admin');await admin.getByRole('heading',{name:'Admin Panel',exact:true}).waitFor();assert.equal(await admin.locator('.tg-access-page').count(),0);
 // Entry-bundle outage: shell still fills the viewport and offers recovery.
 const outage=await context.newPage();await outage.route(/\/(?:assets\/index-[^/]+\.js|src\/bootstrap\.js)/,r=>r.abort());await outage.goto(base+'/');await outage.getByText('Panel files could not load. Check your connection and reload.').waitFor();assert.equal(await outage.locator('#boot-reload').isVisible(),true);assert.equal(await outage.evaluate(()=>getComputedStyle(document.body).margin),'0px');assert(await outage.locator('.boot-screen').evaluate(el=>el.getBoundingClientRect().height>=innerHeight));await outage.screenshot({path:'/home/user/telegram-startup-recovery.png'});
 for(const width of [320,768,1280]){await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.deepEqual(errors,[]);console.log('PASS: direct/deep URLs blocked before customer bundle import, API denial, fake launch rejected, signed Mini App works, cookie-only API blocked, copied URL still restricted, expiry restriction, browser admin login preserved, old timeout API absent, missing-entry recovery and 320/390/768/1280 layouts.');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
