const path=require('node:path'), fs=require('node:fs');
const tools=require('node:module').createRequire(path.resolve(process.env.BROWSER_TOOLS_DIR||'../browser-tools','package.json'));
const {chromium:p}=tools('playwright-core'), c=tools('@sparticuz/chromium').default;
(async()=>{
 const browser=await p.launch({executablePath:process.env.CHROMIUM_PATH||await c.executablePath(),args:[...c.args.filter(a=>a!=='--single-process'),'--disable-gpu'],headless:true});
 try{
 const page=await browser.newPage({viewport:{width:390,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://telegram.org/**',r=>r.fulfill({body:'',contentType:'application/javascript'}));
 const out=process.env.SCREENSHOT_DIR||'/tmp/welcome-checks';fs.mkdirSync(out,{recursive:true});
 await page.request.post('http://127.0.0.1:5173/api/__preview_reset');
 await page.goto('http://127.0.0.1:5173/');
 await page.locator('.bottomnav button').filter({hasText:'Deploy Bot'}).click();
 await page.locator('.welcome-product').click();
 if(await page.getByText('Client / bot name').count())throw Error('Client name field remains');
 await page.getByLabel('Enter your bot token').fill('123456789:synthetic-test-token-only-000000');
 await page.getByRole('button',{name:'Verify',exact:true}).click();await page.getByText('Verified · @demo_welcome_bot').waitFor();
 await page.getByRole('button',{name:'Use my ID'}).click();
 if(await page.getByLabel('Send your ID').inputValue()!=='123456789')throw Error('Use my ID failed');
 await page.locator('.welcome-checkout-title').scrollIntoViewIfNeeded();
 await page.screenshot({path:path.join(out,'checkout-mobile.png'),animations:'disabled'});
 await page.getByLabel('Coupon code (optional)').fill('DEMO10');
 await page.getByRole('button',{name:'Apply',exact:true}).click();
 await page.getByText('₹900',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Purchase',exact:true}).scrollIntoViewIfNeeded();
 await page.screenshot({path:path.join(out,'summary-mobile.png'),animations:'disabled'});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
 await page.getByRole('button',{name:'Purchase',exact:true}).click();
 await page.getByRole('button',{name:'View order status',exact:true}).click();await page.getByText('provisioning',{exact:true}).waitFor();
 await page.evaluate(()=>{window.open=url=>{window.__openedBot=url;return null;};});
 await page.getByRole('button',{name:'Manage in Telegram',exact:true}).click();
 if(await page.evaluate(()=>window.__openedBot)!=='https://t.me/demo_welcome_bot?start=manage')throw Error('Wrong bot target');
 await page.locator('.bottomnav button').filter({hasText:'Orders'}).click();
 await page.getByText('My Orders',{exact:true}).waitFor();
 await page.getByText('Demo APK',{exact:true}).waitFor();
 await page.getByText('@demo_welcome_bot',{exact:true}).waitFor();
 await page.getByText('Demo variant',{exact:true}).waitFor();
 await page.getByRole('button',{name:/^Fake sites/}).click();
 const download=page.getByRole('link',{name:'Download fake APK',exact:true});
 if(await download.getAttribute('href')!=='/api/orders/1/fake-sites/9/download')throw Error('Wrong extra variant download');
 await page.getByRole('button',{name:/^Bots/}).click();
 await page.getByRole('button',{name:'Manage in Telegram',exact:true}).click();
 if(await page.evaluate(()=>window.__openedBot)!=='https://t.me/demo_welcome_bot?start=manage')throw Error('Wrong order bot target');
 if(/\bcoins?\b/i.test(await page.locator('body').innerText()))throw Error('Coin wording remains in customer orders');
 await page.setViewportSize({width:1440,height:1000});
 await page.goto('http://127.0.0.1:5173/admin');
 await page.locator('.admin-side-nav button').filter({hasText:'Deploy Bot'}).click();await page.getByRole('button',{name:/Manage Welcome Bot/}).click();
 await page.getByRole('button',{name:'Plans & pricing',exact:true}).click();
 await page.getByLabel('Purchase price ₹',{exact:true}).first().fill('1100');
 await page.getByRole('button',{name:'Save plans',exact:true}).click();
 await page.getByText('Saved',{exact:true}).waitFor();
 await page.locator('.admin-topbar').scrollIntoViewIfNeeded();
 await page.screenshot({path:path.join(out,'admin-plans-desktop.png'),animations:'disabled'});
 await page.getByRole('button',{name:'Bot controls',exact:true}).click();
 await page.getByRole('button',{name:'Statistics',exact:true}).click();
 await page.locator('.welcome-admin-result').waitFor();
 await page.setViewportSize({width:320,height:780});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Admin 320px overflow');
 if(errors.length)throw Error(errors.join('\n'));
 console.log('PASS: Chromium mobile ₹ checkout, verification, own-bot link, unified order filters/downloads, coupon, wallet purchase, admin pricing save and runtime controls; no runtime errors/overflow.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
